<a href="https://colab.research.google.com/github/TTS-77/Cyclone-AI/blob/main/Notebook/Filtering_IBTrACS_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Filtering IBTrACS Data

In [ ]:



import pandas as pd
import numpy as np
import os

print("Libraries loaded successfully!")

Libraries loaded successfully!

In [ ]:
from google.colab import files

uploaded = files.upload()

print("\nUploaded file:")
for filename in uploaded.keys():
    print(filename)

Saving ibtracs.NI.list.v04r01.csv to ibtracs.NI.list.v04r01.csv

Uploaded file:
ibtracs.NI.list.v04r01.csv

In [ ]:
ibtracs_file = "ibtracs.NI.list.v04r01.csv"

ibtracs = pd.read_csv(
    ibtracs_file,
    skiprows=[1],
    low_memory=False
)

print("Dataset loaded successfully!")
print("Shape:", ibtracs.shape)

Dataset loaded successfully!
Shape: (62848, 174)

In [ ]:
print("Number of columns:", len(ibtracs.columns))

for i, col in enumerate(ibtracs.columns):
    print(i, col)

Number of columns: 174
0 SID
1 SEASON
2 NUMBER
3 BASIN
4 SUBBASIN
5 NAME
6 ISO_TIME
7 NATURE
8 LAT
9 LON
10 WMO_WIND
11 WMO_PRES
12 WMO_AGENCY
13 TRACK_TYPE
14 DIST2LAND
15 LANDFALL
16 IFLAG
17 USA_AGENCY
18 USA_ATCF_ID
19 USA_LAT
20 USA_LON
21 USA_RECORD
22 USA_STATUS
23 USA_WIND
24 USA_PRES
25 USA_SSHS
26 USA_R34_NE
27 USA_R34_SE
28 USA_R34_SW
29 USA_R34_NW
30 USA_R50_NE
31 USA_R50_SE
32 USA_R50_SW
33 USA_R50_NW
34 USA_R64_NE
35 USA_R64_SE
36 USA_R64_SW
37 USA_R64_NW
38 USA_POCI
39 USA_ROCI
40 USA_RMW
41 USA_EYE
42 TOKYO_LAT
43 TOKYO_LON
44 TOKYO_GRADE
45 TOKYO_WIND
46 TOKYO_PRES
47 TOKYO_R50_DIR
48 TOKYO_R50_LONG
49 TOKYO_R50_SHORT
50 TOKYO_R30_DIR
51 TOKYO_R30_LONG
52 TOKYO_R30_SHORT
53 TOKYO_LAND
54 CMA_LAT
55 CMA_LON
56 CMA_CAT
57 CMA_WIND
58 CMA_PRES
59 HKO_LAT
60 HKO_LON
61 HKO_CAT
62 HKO_WIND
63 HKO_PRES
64 KMA_LAT
65 KMA_LON
66 KMA_CAT
67 KMA_WIND
68 KMA_PRES
69 KMA_R50_DIR
70 KMA_R50_LONG
71 KMA_R50_SHORT
72 KMA_R30_DIR
73 KMA_R30_LONG
74 KMA_R30_SHORT
75 NEWDELHI_LAT
76 NEWDELHI_LON
77 NEWDELHI_GRADE
78 NEWDELHI_WIND
79 NEWDELHI_PRES
80 NEWDELHI_CI
81 NEWDELHI_DP
82 NEWDELHI_POCI
83 REUNION_LAT
84 REUNION_LON
85 REUNION_TYPE
86 REUNION_WIND
87 REUNION_PRES
88 REUNION_TNUM
89 REUNION_CI
90 REUNION_RMW
91 REUNION_R34_NE
92 REUNION_R34_SE
93 REUNION_R34_SW
94 REUNION_R34_NW
95 REUNION_R50_NE
96 REUNION_R50_SE
97 REUNION_R50_SW
98 REUNION_R50_NW
99 REUNION_R64_NE
100 REUNION_R64_SE
101 REUNION_R64_SW
102 REUNION_R64_NW
103 BOM_LAT
104 BOM_LON
105 BOM_TYPE
106 BOM_WIND
107 BOM_PRES
108 BOM_TNUM
109 BOM_CI
110 BOM_RMW
111 BOM_R34_NE
112 BOM_R34_SE
113 BOM_R34_SW
114 BOM_R34_NW
115 BOM_R50_NE
116 BOM_R50_SE
117 BOM_R50_SW
118 BOM_R50_NW
119 BOM_R64_NE
120 BOM_R64_SE
121 BOM_R64_SW
122 BOM_R64_NW
123 BOM_ROCI
124 BOM_POCI
125 BOM_EYE
126 BOM_POS_METHOD
127 BOM_PRES_METHOD
128 NADI_LAT
129 NADI_LON
130 NADI_CAT
131 NADI_WIND
132 NADI_PRES
133 WELLINGTON_LAT
134 WELLINGTON_LON
135 WELLINGTON_WIND
136 WELLINGTON_PRES
137 DS824_LAT
138 DS824_LON
139 DS824_STAGE
140 DS824_WIND
141 DS824_PRES
142 TD9636_LAT
143 TD9636_LON
144 TD9636_STAGE
145 TD9636_WIND
146 TD9636_PRES
147 TD9635_LAT
148 TD9635_LON
149 TD9635_WIND
150 TD9635_PRES
151 TD9635_ROCI
152 NEUMANN_LAT
153 NEUMANN_LON
154 NEUMANN_CLASS
155 NEUMANN_WIND
156 NEUMANN_PRES
157 MLC_LAT
158 MLC_LON
159 MLC_CLASS
160 MLC_WIND
161 MLC_PRES
162 USA_GUST
163 BOM_GUST
164 BOM_GUST_PER
165 REUNION_GUST
166 REUNION_GUST_PER
167 USA_SEAHGT
168 USA_SEARAD_NE
169 USA_SEARAD_SE
170 USA_SEARAD_SW
171 USA_SEARAD_NW
172 STORM_SPEED
173 STORM_DIR

In [ ]:
important_columns = [
    "SID",
    "SEASON",
    "NAME",
    "ISO_TIME",
    "LAT",
    "LON",
    "USA_WIND",
    "USA_PRES"
]

print(ibtracs[important_columns].head(10))

             SID  SEASON     NAME             ISO_TIME   LAT   LON USA_WIND  \
0  1842298N11080    1842  UNNAMED  1842-10-25 03:00:00  10.9  80.3
1  1842298N11080    1842  UNNAMED  1842-10-25 06:00:00  10.9  79.8
2  1842298N11080    1842  UNNAMED  1842-10-25 09:00:00  10.8  79.4
3  1842298N11080    1842  UNNAMED  1842-10-25 12:00:00  10.8  78.9
4  1842298N11080    1842  UNNAMED  1842-10-25 15:00:00  10.8  78.4
5  1842298N11080    1842  UNNAMED  1842-10-25 18:00:00  10.8  77.9
6  1842298N11080    1842  UNNAMED  1842-10-25 21:00:00  10.8  77.4
7  1842298N11080    1842  UNNAMED  1842-10-26 00:00:00  10.8  76.9
8  1842298N11080    1842  UNNAMED  1842-10-26 03:00:00  10.8  76.4
9  1842298N11080    1842  UNNAMED  1842-10-26 06:00:00  10.8  75.8

  USA_PRES
0
1
2
3
4
5
6
7
8
9

In [ ]:
ibtracs["ISO_TIME"] = pd.to_datetime(
    ibtracs["ISO_TIME"],
    errors="coerce"
)

for col in ["LAT", "LON", "USA_WIND", "USA_PRES"]:
    ibtracs[col] = pd.to_numeric(
        ibtracs[col],
        errors="coerce"
    )

print(ibtracs[important_columns].dtypes)

SID                 object
SEASON               int64
NAME                object
ISO_TIME    datetime64[ns]
LAT                float64
LON                float64
USA_WIND           float64
USA_PRES           float64
dtype: object

In [ ]:
print("Total observations:", len(ibtracs))

print(
    "Time range:",
    ibtracs["ISO_TIME"].min(),
    "to",
    ibtracs["ISO_TIME"].max()
)

print(
    "Latitude range:",
    ibtracs["LAT"].min(),
    "to",
    ibtracs["LAT"].max()
)

print(
    "Longitude range:",
    ibtracs["LON"].min(),
    "to",
    ibtracs["LON"].max()
)

Total observations: 62848
Time range: 1842-10-25 03:00:00 to 2025-12-02 18:00:00
Latitude range: 0.7 to 83.0
Longitude range: -87.7 to 163.7

In [ ]:
storm_summary = (
    ibtracs[
        ["SID", "SEASON", "NAME"]
    ]
    .drop_duplicates()
)

print("Number of unique cyclones:",
      storm_summary["SID"].nunique())

print("\nNumber of cyclones by year:")

print(
    storm_summary
    .groupby("SEASON")
    .size()
    .to_string()
)

Number of unique cyclones: 1858

Number of cyclones by year:
SEASON
1842     1
1845     1
1854     1
1877     9
1878     9
1879    10
1880    10
1881    12
1882    12
1883    11
1884    15
1885    11
1886    11
1887    13
1888    14
1889    12
1890    10
1891    13
1892    12
1893    12
1894    12
1895    11
1896    10
1897    12
1898    14
1899     7
1900    10
1901     6
1902    13
1903    14
1904     9
1905    10
1906    11
1907    15
1908     9
1909     8
1910     6
1911     7
1912     9
1913    10
1914     8
1915     9
1916    14
1917    10
1918    11
1919    11
1920    11
1921    10
1922    13
1923    16
1924    13
1925    20
1926    13
1927    18
1928    13
1929    15
1930    14
1931    11
1932    15
1933    16
1934    16
1935    15
1936    19
1937    19
1938    10
1939    19
1940    16
1941    19
1942    14
1943    14
1944    19
1945    15
1946    18
1947    19
1948    20
1949    13
1950    16
1951    19
1952    18
1953    11
1954    19
1955    13
1956    15
1957     7
1958    13
1959    15
1960    17
1961    19
1962    16
1963    17
1964    22
1965    21
1966    20
1967    15
1968    13
1969    15
1970    16
1971    17
1972    19
1973    17
1974    12
1975    21
1976    14
1977     8
1978     6
1979     8
1980     5
1981     4
1982    19
1983    10
1984     8
1985    17
1986     8
1987    13
1988    10
1989    10
1990    12
1991     9
1992    15
1993     6
1994     6
1995    10
1996    12
1997    10
1998    13
1999    10
2000     6
2001     7
2002     6
2003     7
2004    11
2005    16
2006    13
2007     6
2008    10
2009     8
2010     8
2011    10
2012     5
2013    10
2014     8
2015    12
2016     8
2017    12
2018    15
2019    11
2020    10
2021    10
2022    15
2023    10
2024    13
2025    17

In [ ]:
storms = (
    ibtracs[
        ["SID", "SEASON", "NAME"]
    ]
    .drop_duplicates()
    .sort_values(["SEASON", "NAME"])
)

print(storms.to_string(index=False))

          SID  SEASON             NAME
1842298N11080    1842          UNNAMED
1845336N10074    1845          UNNAMED
1854303N14072    1854          UNNAMED
1877135N10083    1877          UNNAMED
1877192N21090    1877          UNNAMED
1877218N21090    1877          UNNAMED
1877220N22092    1877          UNNAMED
1877226N21089    1877          UNNAMED
1877230N20091    1877          UNNAMED
1877241N20088    1877          UNNAMED
1877249N20088    1877          UNNAMED
1877307N18091    1877          UNNAMED
1878202N18087    1878          UNNAMED
1878215N20086    1878          UNNAMED
1878218N20089    1878          UNNAMED
1878256N19090    1878          UNNAMED
1878261N18090    1878          UNNAMED
1878287N16084    1878          UNNAMED
1878301N15084    1878          UNNAMED
1878308N16084    1878          UNNAMED
1878339N17087    1878          UNNAMED
1879140N13081    1879          UNNAMED
1879141N12073    1879          UNNAMED
1879149N21087    1879          UNNAMED
1879220N21088    1879          UNNAMED
1879256N21090    1879          UNNAMED
1879265N20089    1879          UNNAMED
1879284N19092    1879          UNNAMED
1879299N20092    1879          UNNAMED
1879305N15097    1879          UNNAMED
1879322N13081    1879          UNNAMED
1880153N20089    1880          UNNAMED
1880177N19088    1880          UNNAMED
1880196N20089    1880          UNNAMED
1880214N20088    1880          UNNAMED
1880233N21089    1880          UNNAMED
1880257N19089    1880          UNNAMED
1880265N20088    1880          UNNAMED
1880267N21088    1880          UNNAMED
1880287N17085    1880          UNNAMED
1880325N10082    1880          UNNAMED
1881146N14067    1881          UNNAMED
1881146N20090    1881          UNNAMED
1881154N20089    1881          UNNAMED
1881157N21088    1881          UNNAMED
1881165N21089    1881          UNNAMED
1881183N21088    1881          UNNAMED
1881194N21090    1881          UNNAMED
1881214N20087    1881          UNNAMED
1881230N21089    1881          UNNAMED
1881254N20089    1881          UNNAMED
1881277N17085    1881          UNNAMED
1881315N11082    1881          UNNAMED
1882192N21089    1882          UNNAMED
1882199N21089    1882          UNNAMED
1882204N20089    1882          UNNAMED
1882212N20088    1882          UNNAMED
1882231N21089    1882          UNNAMED
1882249N20090    1882          UNNAMED
1882257N18087    1882          UNNAMED
1882269N16092    1882          UNNAMED
1882285N13085    1882          UNNAMED
1882300N11089    1882          UNNAMED
1882325N09089    1882          UNNAMED
1882332N10087    1882          UNNAMED
1883165N21087    1883          UNNAMED
1883177N20089    1883          UNNAMED
1883183N22068    1883          UNNAMED
1883184N20090    1883          UNNAMED
1883187N20089    1883          UNNAMED
1883193N19089    1883          UNNAMED
1883196N22068    1883          UNNAMED
1883207N21090    1883          UNNAMED
1883234N18088    1883          UNNAMED
1883314N11095    1883          UNNAMED
1883338N17086    1883          UNNAMED
1884135N11090    1884          UNNAMED
1884171N20088    1884          UNNAMED
1884182N21089    1884          UNNAMED
1884191N21089    1884          UNNAMED
1884197N20088    1884          UNNAMED
1884200N21089    1884          UNNAMED
1884215N21088    1884          UNNAMED
1884251N20089    1884          UNNAMED
1884261N17088    1884          UNNAMED
1884290N10082    1884          UNNAMED
1884298N16085    1884          UNNAMED
1884305N19090    1884          UNNAMED
1884310N11082    1884          UNNAMED
1884325N13083    1884          UNNAMED
1884349N08083    1884          UNNAMED
1885150N13061    1885          UNNAMED
1885156N12071    1885          UNNAMED
1885167N21090    1885          UNNAMED
1885177N21087    1885          UNNAMED
1885195N20088    1885          UNNAMED
1885204N21089    1885          UNNAMED
1885228N21088    1885          UNNAMED
1885258N21088    1885          UNNAMED
1885262N15093    1885          UNNAMED
1885306N13082    1885          UNNAMED
1885322N12082    1885          UNNAMED
1886143N11082    1886          UNNAMED
1886144N07062    1886          UNNAMED
1886166N20089    1886          UNNAMED
1886198N20088    1886          UNNAMED
1886224N16082    1886          UNNAMED
1886261N20088    1886          UNNAMED
1886270N15089    1886          UNNAMED
1886290N16087    1886          UNNAMED
1886306N10092    1886          UNNAMED
1886319N11094    1886          UNNAMED
1886342N11085    1886          UNNAMED
1887141N16092    1887          UNNAMED
1887158N18071    1887          UNNAMED
1887162N18088    1887          UNNAMED
1887170N21088    1887          UNNAMED
1887188N25082    1887          UNNAMED
1887191N23088    1887          UNNAMED
1887193N23091    1887          UNNAMED
1887198N21088    1887          UNNAMED
1887229N18087    1887          UNNAMED
1887233N21088    1887          UNNAMED
1887252N21089    1887          UNNAMED
1887264N20088    1887          UNNAMED
1887280N11085    1887          UNNAMED
1888132N10081    1888          UNNAMED
1888184N24088    1888          UNNAMED
1888194N19087    1888          UNNAMED
1888201N21089    1888          UNNAMED
1888208N25083    1888          UNNAMED
1888217N21088    1888          UNNAMED
1888228N23088    1888          UNNAMED
1888234N21089    1888          UNNAMED
1888250N20087    1888          UNNAMED
1888257N15099    1888          UNNAMED
1888275N15094    1888          UNNAMED
1888301N11091    1888          UNNAMED
1888309N16068    1888          UNNAMED
1888347N10087    1888          UNNAMED
1889153N14070    1889          UNNAMED
1889159N15087    1889          UNNAMED
1889200N21089    1889          UNNAMED
1889208N21089    1889          UNNAMED
1889217N21089    1889          UNNAMED
1889228N21089    1889          UNNAMED
1889260N17088    1889          UNNAMED
1889288N14083    1889          UNNAMED
1889298N21088    1889          UNNAMED
1889322N13084    1889          UNNAMED
1889351N10081    1889          UNNAMED
1889357N14087    1889          UNNAMED
1890125N12094    1890          UNNAMED
1890153N19069    1890          UNNAMED
1890169N19086    1890          UNNAMED
1890173N23089    1890          UNNAMED
1890182N20088    1890          UNNAMED
1890192N25084    1890          UNNAMED
1890224N24087    1890          UNNAMED
1890266N18085    1890          UNNAMED
1890283N14085    1890          UNNAMED
1890294N17090    1890          UNNAMED
1891140N10082    1891          UNNAMED
1891205N22088    1891          UNNAMED
1891213N20091    1891          UNNAMED
1891224N23089    1891          UNNAMED
1891245N20089    1891          UNNAMED
1891248N21089    1891          UNNAMED
1891254N20088    1891          UNNAMED
1891260N19087    1891          UNNAMED
1891263N16097    1891          UNNAMED
1891293N10084    1891          UNNAMED
1891305N08074    1891          UNNAMED
1891305N10097    1891          UNNAMED
1891324N12088    1891          UNNAMED
1892119N17061    1892          UNNAMED
1892153N20070    1892          UNNAMED
1892160N19089    1892          UNNAMED
1892191N20089    1892          UNNAMED
1892200N24086    1892          UNNAMED
1892204N23087    1892          UNNAMED
1892242N18087    1892          UNNAMED
1892251N18091    1892          UNNAMED
1892263N15086    1892          UNNAMED
1892288N10092    1892          UNNAMED
1892292N14094    1892          UNNAMED
1892300N11086    1892          UNNAMED
1893115N12092    1893          UNNAMED
1893143N20087    1893          UNNAMED
1893163N13092    1893          UNNAMED
1893176N23091    1893          UNNAMED
1893212N20088    1893          UNNAMED
1893244N21088    1893          UNNAMED
1893252N18090    1893          UNNAMED
1893264N18089    1893          UNNAMED
1893293N16091    1893          UNNAMED
1893298N11096    1893          UNNAMED
1893308N10084    1893          UNNAMED
1893316N12073    1893          UNNAMED
1894117N13093    1894          UNNAMED
1894164N23091    1894          UNNAMED
1894172N20087    1894          UNNAMED
1894184N25089    1894          UNNAMED
1894192N20087    1894          UNNAMED
1894197N20089    1894          UNNAMED
1894205N22088    1894          UNNAMED
1894225N23088    1894          UNNAMED
1894270N20087    1894          UNNAMED
1894275N21088    1894          UNNAMED
1894296N15068    1894          UNNAMED
1894303N13090    1894          UNNAMED
1895112N11086    1895          UNNAMED
1895165N18070    1895          UNNAMED
1895170N21088    1895          UNNAMED
1895179N21088    1895          UNNAMED
1895199N20088    1895          UNNAMED
1895211N21088    1895          UNNAMED
1895218N20088    1895          UNNAMED
1895247N17087    1895          UNNAMED
1895259N18090    1895          UNNAMED
1895273N18087    1895          UNNAMED
1895344N12089    1895          UNNAMED
1896146N13070    1896          UNNAMED
1896170N21089    1896          UNNAMED
1896178N21090    1896          UNNAMED
1896204N21089    1896          UNNAMED
1896208N21090    1896          UNNAMED
1896214N21089    1896          UNNAMED
1896226N21088    1896          UNNAMED
1896233N22089    1896          UNNAMED
1896257N20090    1896          UNNAMED
1896319N06079    1896          UNNAMED
1897133N15096    1897          UNNAMED
1897166N20089    1897          UNNAMED
1897190N21088    1897          UNNAMED
1897191N20070    1897          UNNAMED
1897195N25088    1897          UNNAMED
1897225N21088    1897          UNNAMED
1897252N19085    1897          UNNAMED
1897255N21070    1897          UNNAMED
1897266N17090    1897          UNNAMED
1897275N18084    1897          UNNAMED
1897294N14096    1897          UNNAMED
1897360N13085    1897          UNNAMED
1898125N13095    1898          UNNAMED
1898151N11059    1898          UNNAMED
1898152N11060    1898          UNNAMED
1898164N18086    1898          UNNAMED
1898183N21089    1898          UNNAMED
1898197N25085    1898          UNNAMED
1898221N21089    1898          UNNAMED
1898225N24090    1898          UNNAMED
1898233N22091    1898          UNNAMED
1898240N24090    1898          UNNAMED
1898254N18087    1898          UNNAMED
1898263N21089    1898          UNNAMED
1898282N13085    1898          UNNAMED
1898309N11085    1898          UNNAMED
1899118N13094    1899          UNNAMED
1899194N23089    1899          UNNAMED
1899220N16094    1899          UNNAMED
1899239N20087    1899          UNNAMED
1899252N18092    1899          UNNAMED
1899264N17089    1899          UNNAMED
1899285N11082    1899          UNNAMED
1900162N19088    1900          UNNAMED
1900173N21088    1900          UNNAMED
1900194N21088    1900          UNNAMED
1900210N19088    1900          UNNAMED
1900221N20088    1900          UNNAMED
1900227N20091    1900          UNNAMED
1900237N21090    1900          UNNAMED
1900258N21088    1900          UNNAMED
1900277N15087    1900          UNNAMED
1900296N11085    1900          UNNAMED
1901115N06074    1901          UNNAMED
1901264N17085    1901          UNNAMED
1901278N17087    1901          UNNAMED
1901286N17087    1901          UNNAMED
1901318N16084    1901          UNNAMED
1901328N12088    1901          UNNAMED
1902125N14095    1902          UNNAMED
1902127N12055    1902          UNNAMED
1902162N19070    1902          UNNAMED
1902196N21089    1902          UNNAMED
1902208N22088    1902          UNNAMED
1902231N18086    1902          UNNAMED
1902236N20088    1902          UNNAMED
1902244N21088    1902          UNNAMED
1902266N18090    1902          UNNAMED
1902287N14064    1902          UNNAMED
1902300N09085    1902          UNNAMED
1902301N11065    1902          UNNAMED
1902341N09063    1902          UNNAMED
1903142N16072    1903          UNNAMED
1903163N14072    1903          UNNAMED
1903176N22088    1903          UNNAMED
1903193N18087    1903          UNNAMED
1903195N21070    1903          UNNAMED
1903204N21087    1903          UNNAMED
1903213N20087    1903          UNNAMED
1903241N17085    1903          UNNAMED
1903254N23089    1903          UNNAMED
1903278N19086    1903          UNNAMED
1903301N13084    1903          UNNAMED
1903308N11087    1903          UNNAMED
1903317N14087    1903          UNNAMED
1903329N10087    1903          UNNAMED
1904146N14083    1904          UNNAMED
1904162N21089    1904          UNNAMED
1904184N22085    1904          UNNAMED
1904189N23089    1904          UNNAMED
1904225N20089    1904          UNNAMED
1904233N21089    1904          UNNAMED
1904254N18086    1904          UNNAMED
1904288N13085    1904          UNNAMED
1904326N13089    1904          UNNAMED
1905181N21087    1905          UNNAMED
1905186N22089    1905          UNNAMED
1905192N21090    1905          UNNAMED
1905200N21089    1905          UNNAMED
1905250N19087    1905          UNNAMED
1905265N16087    1905          UNNAMED
1905271N22089    1905          UNNAMED
1905295N17067    1905          UNNAMED
1905296N17086    1905          UNNAMED
1905342N15092    1905          UNNAMED
1906015N08084    1906          UNNAMED
1906169N19086    1906          UNNAMED
1906188N24090    1906          UNNAMED
1906202N20087    1906          UNNAMED
1906206N21091    1906          UNNAMED
1906239N20086    1906          UNNAMED
1906255N22089    1906          UNNAMED
1906267N17088    1906          UNNAMED
1906300N11085    1906          UNNAMED
1906303N12058    1906          UNNAMED
1906360N11083    1906          UNNAMED
1907067N08085    1907          UNNAMED
1907135N18092    1907          UNNAMED
1907155N20067    1907          UNNAMED
1907164N16085    1907          UNNAMED
1907169N21067    1907          UNNAMED
1907174N20090    1907          UNNAMED
1907224N21088    1907          UNNAMED
1907230N23088    1907          UNNAMED
1907238N21087    1907          UNNAMED
1907244N23089    1907          UNNAMED
1907278N21090    1907          UNNAMED
1907286N15091    1907          UNNAMED
1907313N12062    1907          UNNAMED
1907316N10087    1907          UNNAMED
1907328N09096    1907          UNNAMED
1908168N21089    1908          UNNAMED
1908214N20086    1908          UNNAMED
1908220N21088    1908          UNNAMED
1908241N19087    1908          UNNAMED
1908268N17085    1908          UNNAMED
1908299N10074    1908          UNNAMED
1908306N10084    1908          UNNAMED
1908314N14093    1908          UNNAMED
1908365N08083    1908          UNNAMED
1909123N09084    1909          UNNAMED
1909132N14090    1909          UNNAMED
1909212N21089    1909          UNNAMED
1909245N15084    1909          UNNAMED
1909264N21088    1909          UNNAMED
1909288N14094    1909          UNNAMED
1909297N16094    1909          UNNAMED
1909336N12085    1909          UNNAMED
1910103N12090    1910          UNNAMED
1910182N20090    1910          UNNAMED
1910213N19087    1910          UNNAMED
1910251N22088    1910          UNNAMED
1910307N09083    1910          UNNAMED
1910316N15086    1910          UNNAMED
1911105N14087    1911          UNNAMED
1911143N09070    1911          UNNAMED
1911160N18089    1911          UNNAMED
1911169N21088    1911          UNNAMED
1911240N19087    1911          UNNAMED
1911263N16093    1911          UNNAMED
1911293N10097    1911          UNNAMED
1912209N20088    1912          UNNAMED
1912214N18086    1912          UNNAMED
1912241N20087    1912          UNNAMED
1912249N22089    1912          UNNAMED
1912266N15085    1912          UNNAMED
1912299N15071    1912          UNNAMED
1912302N08089    1912          UNNAMED
1912324N08080    1912          UNNAMED
1912352N06082    1912          UNNAMED
1913197N19087    1913          UNNAMED
1913204N21090    1913          UNNAMED
1913211N22089    1913          UNNAMED
1913218N23090    1913          UNNAMED
1913236N24079    1913          UNNAMED
1913242N20087    1913          UNNAMED
1913286N18086    1913          UNNAMED
1913304N15093    1913          UNNAMED
1913311N07086    1913          UNNAMED
1913349N06085    1913          UNNAMED
1914133N13091    1914          UNNAMED
1914153N18089    1914          UNNAMED
1914175N19087    1914          UNNAMED
1914191N19087    1914          UNNAMED
1914216N24086    1914          UNNAMED
1914256N18083    1914          UNNAMED
1914275N11094    1914          UNNAMED
1914353N09085    1914          UNNAMED
1915174N17088    1915          UNNAMED
1915213N19089    1915          UNNAMED
1915238N18087    1915          UNNAMED
1915249N19086    1915          UNNAMED
1915273N17089    1915          UNNAMED
1915283N19087    1915          UNNAMED
1915308N13087    1915          UNNAMED
1915319N17085    1915          UNNAMED
1915337N10090    1915          UNNAMED
1916125N13091    1916          UNNAMED
1916146N12062    1916          UNNAMED
1916156N19091    1916          UNNAMED
1916163N21088    1916          UNNAMED
1916226N21089    1916          UNNAMED
1916232N25080    1916          UNNAMED
1916263N18091    1916          UNNAMED
1916276N18088    1916          UNNAMED
1916289N10088    1916          UNNAMED
1916295N12088    1916          UNNAMED
1916301N15092    1916          UNNAMED
1916306N18090    1916          UNNAMED
1916312N15095    1916          UNNAMED
1916326N09088    1916          UNNAMED
1917121N10084    1917          UNNAMED
1917164N22089    1917          UNNAMED
1917165N20067    1917          UNNAMED
1917177N20088    1917          UNNAMED
1917211N23090    1917          UNNAMED
1917219N21088    1917          UNNAMED
1917248N18087    1917          UNNAMED
1917274N19089    1917          UNNAMED
1917292N10073    1917          UNNAMED
1917297N11093    1917          UNNAMED
1918014N07086    1918          UNNAMED
1918144N21091    1918          UNNAMED
1918165N21088    1918          UNNAMED
1918209N20089    1918          UNNAMED
1918226N20088    1918          UNNAMED
1918238N24084    1918          UNNAMED
1918247N20088    1918          UNNAMED
1918285N20089    1918          UNNAMED
1918314N10085    1918          UNNAMED
1918321N09083    1918          UNNAMED
1918343N07088    1918          UNNAMED
1919150N13067    1919          UNNAMED
1919182N20087    1919          UNNAMED
1919209N18090    1919          UNNAMED
1919217N21091    1919          UNNAMED
1919223N22089    1919          UNNAMED
1919236N19088    1919          UNNAMED
1919243N20089    1919          UNNAMED
1919266N15089    1919          UNNAMED
1919305N10084    1919          UNNAMED
1919317N14085    1919          UNNAMED
1919363N08086    1919          UNNAMED
1920121N11088    1920          UNNAMED
1920158N14069    1920          UNNAMED
1920172N20087    1920          UNNAMED
1920184N17087    1920          UNNAMED
1920197N17087    1920          UNNAMED
1920203N23089    1920          UNNAMED
1920212N21089    1920          UNNAMED
1920218N21092    1920          UNNAMED
1920238N19088    1920          UNNAMED
1920250N17090    1920          UNNAMED
1920325N10066    1920          UNNAMED
1921096N10084    1921          UNNAMED
1921205N18089    1921          UNNAMED
1921220N21088    1921          UNNAMED
1921245N18089    1921          UNNAMED
1921245N23080    1921          UNNAMED
1921258N18086    1921          UNNAMED
1921277N11097    1921          UNNAMED
1921297N12086    1921          UNNAMED
1921310N11089    1921          UNNAMED
1921361N05086    1921          UNNAMED
1922108N09068    1922          UNNAMED
1922109N09093    1922          UNNAMED
1922188N20089    1922          UNNAMED
1922208N21088    1922          UNNAMED
1922214N23088    1922          UNNAMED
1922231N21088    1922          UNNAMED
1922251N19088    1922          UNNAMED
1922265N20088    1922          UNNAMED
1922288N10091    1922          UNNAMED
1922312N14097    1922          UNNAMED
1922321N12096    1922          UNNAMED
1922329N09089    1922          UNNAMED
1922340N08091    1922          UNNAMED
1923006N06092    1923          UNNAMED
1923117N14093    1923          UNNAMED
1923122N14085    1923          UNNAMED
1923185N23086    1923          UNNAMED
1923200N19087    1923          UNNAMED
1923209N23091    1923          UNNAMED
1923217N23089    1923          UNNAMED
1923222N22091    1923          UNNAMED
1923227N21089    1923          UNNAMED
1923233N21090    1923          UNNAMED
1923258N15086    1923          UNNAMED
1923271N17086    1923          UNNAMED

In [ ]:
print("Missing values in important columns:\n")

print(
    ibtracs[important_columns]
    .isna()
    .sum()
)

Missing values in important columns:

SID             0
SEASON          0
NAME            0
ISO_TIME        0
LAT             0
LON             0
USA_WIND    46486
USA_PRES    55738
dtype: int64

In [ ]:
track = ibtracs[
    [
        "SID",
        "SEASON",
        "NAME",
        "ISO_TIME",
        "LAT",
        "LON",
        "USA_WIND",
        "USA_PRES"
    ]
].copy()

print("Clean track dataset shape:", track.shape)

print(track.head())

Clean track dataset shape: (62848, 8)
             SID  SEASON     NAME            ISO_TIME   LAT   LON  USA_WIND  \
0  1842298N11080    1842  UNNAMED 1842-10-25 03:00:00  10.9  80.3       NaN
1  1842298N11080    1842  UNNAMED 1842-10-25 06:00:00  10.9  79.8       NaN
2  1842298N11080    1842  UNNAMED 1842-10-25 09:00:00  10.8  79.4       NaN
3  1842298N11080    1842  UNNAMED 1842-10-25 12:00:00  10.8  78.9       NaN
4  1842298N11080    1842  UNNAMED 1842-10-25 15:00:00  10.8  78.4       NaN

   USA_PRES
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN

In [ ]:
track = track.dropna(
    subset=["ISO_TIME", "LAT", "LON"]
).copy()

print("After removing missing positions:",
      track.shape)

After removing missing positions: (62848, 8)

In [ ]:
track = track.sort_values(
    ["SID", "ISO_TIME"]
).reset_index(drop=True)

print(track.head(20))

              SID  SEASON     NAME            ISO_TIME   LAT   LON  USA_WIND  \
0   1842298N11080    1842  UNNAMED 1842-10-25 03:00:00  10.9  80.3       NaN
1   1842298N11080    1842  UNNAMED 1842-10-25 06:00:00  10.9  79.8       NaN
2   1842298N11080    1842  UNNAMED 1842-10-25 09:00:00  10.8  79.4       NaN
3   1842298N11080    1842  UNNAMED 1842-10-25 12:00:00  10.8  78.9       NaN
4   1842298N11080    1842  UNNAMED 1842-10-25 15:00:00  10.8  78.4       NaN
5   1842298N11080    1842  UNNAMED 1842-10-25 18:00:00  10.8  77.9       NaN
6   1842298N11080    1842  UNNAMED 1842-10-25 21:00:00  10.8  77.4       NaN
7   1842298N11080    1842  UNNAMED 1842-10-26 00:00:00  10.8  76.9       NaN
8   1842298N11080    1842  UNNAMED 1842-10-26 03:00:00  10.8  76.4       NaN
9   1842298N11080    1842  UNNAMED 1842-10-26 06:00:00  10.8  75.8       NaN
10  1842298N11080    1842  UNNAMED 1842-10-26 09:00:00  10.8  75.3       NaN
11  1842298N11080    1842  UNNAMED 1842-10-26 12:00:00  10.9  74.7       NaN
12  1842298N11080    1842  UNNAMED 1842-10-26 15:00:00  10.9  74.1       NaN
13  1842298N11080    1842  UNNAMED 1842-10-26 18:00:00  11.0  73.5       NaN
14  1842298N11080    1842  UNNAMED 1842-10-26 21:00:00  11.0  73.0       NaN
15  1842298N11080    1842  UNNAMED 1842-10-27 00:00:00  11.1  72.4       NaN
16  1842298N11080    1842  UNNAMED 1842-10-27 03:00:00  11.2  71.9       NaN
17  1842298N11080    1842  UNNAMED 1842-10-27 06:00:00  11.3  71.4       NaN
18  1842298N11080    1842  UNNAMED 1842-10-27 09:00:00  11.3  70.9       NaN
19  1842298N11080    1842  UNNAMED 1842-10-27 12:00:00  11.3  70.5       NaN

    USA_PRES
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
5        NaN
6        NaN
7        NaN
8        NaN
9        NaN
10       NaN
11       NaN
12       NaN
13       NaN
14       NaN
15       NaN
16       NaN
17       NaN
18       NaN
19       NaN

In [ ]:
track.to_csv(
    "ibtracs_NI_clean.csv",
    index=False
)

print("Saved successfully!")
print("File:", "ibtracs_NI_clean.csv")

Saved successfully!
File: ibtracs_NI_clean.csv

In [ ]:
from google.colab import files

files.download("ibtracs_NI_clean.csv")

In [ ]:
# Select the period we want for the ML project
model_track = track[
    (track["SEASON"] >= 2000) &
    (track["SEASON"] <= 2025)
].copy()

print("========== MODEL DATA SUMMARY ==========")

print("Observations:", len(model_track))
print("Unique cyclones:", model_track["SID"].nunique())

print(
    "Years:",
    model_track["SEASON"].min(),
    "to",
    model_track["SEASON"].max()
)

print(
    "Latitude:",
    model_track["LAT"].min(),
    "to",
    model_track["LAT"].max()
)

print(
    "Longitude:",
    model_track["LON"].min(),
    "to",
    model_track["LON"].max()
)

print("\nMissing values:")
print(model_track[[
    "LAT", "LON", "USA_WIND", "USA_PRES"
]].isna().sum())

print("\nCyclones per year:")
print(
    model_track[
        ["SID", "SEASON", "NAME"]
    ]
    .drop_duplicates()
    .groupby("SEASON")
    .size()
    .to_string()
)

========== MODEL DATA SUMMARY ==========
Observations: 9622
Unique cyclones: 264
Years: 2000 to 2025
Latitude: 0.7 to 29.2
Longitude: 41.8 to 149.8

Missing values:
LAT            0
LON            0
USA_WIND    2404
USA_PRES    2598
dtype: int64

Cyclones per year:
SEASON
2000     6
2001     7
2002     6
2003     7
2004    11
2005    16
2006    13
2007     6
2008    10
2009     8
2010     8
2011    10
2012     5
2013    10
2014     8
2015    12
2016     8
2017    12
2018    15
2019    11
2020    10
2021    10
2022    15
2023    10
2024    13
2025    17

In [ ]:
# Define the North Indian Ocean model region

NORTH = 30.0
SOUTH = 0.0
WEST = 40.0
EAST = 110.0

noi_track = model_track[
    (model_track["LAT"] >= SOUTH) &
    (model_track["LAT"] <= NORTH) &
    (model_track["LON"] >= WEST) &
    (model_track["LON"] <= EAST)
].copy()

print("========== NORTH INDIAN OCEAN FILTER ==========")

print("Observations:", len(noi_track))
print("Unique cyclones:", noi_track["SID"].nunique())

print(
    "Latitude:",
    noi_track["LAT"].min(),
    "to",
    noi_track["LAT"].max()
)

print(
    "Longitude:",
    noi_track["LON"].min(),
    "to",
    noi_track["LON"].max()
)

print(
    "Years:",
    noi_track["SEASON"].min(),
    "to",
    noi_track["SEASON"].max()
)

print("\nMissing values:")
print(
    noi_track[
        ["LAT", "LON", "USA_WIND", "USA_PRES"]
    ].isna().sum()
)

========== NORTH INDIAN OCEAN FILTER ==========
Observations: 9149
Unique cyclones: 264
Latitude: 0.7 to 29.2
Longitude: 41.8 to 110.0
Years: 2000 to 2025

Missing values:
LAT            0
LON            0
USA_WIND    2372
USA_PRES    2566
dtype: int64

In [ ]:
noi_storms = (
    noi_track[
        ["SID", "SEASON", "NAME"]
    ]
    .drop_duplicates()
    .sort_values(["SEASON", "NAME"])
)

print("Number of storms:", len(noi_storms))
print()
print(noi_storms.to_string(index=False))

Number of storms: 264

          SID  SEASON             NAME
2000088N08090    2000          UNNAMED
2000236N17084    2000          UNNAMED
2000289N15089    2000          UNNAMED
2000299N13093    2000          UNNAMED
2000331N09092    2000          UNNAMED
2000358N08086    2000          UNNAMED
2001141N14068    2001          UNNAMED
2001163N20087    2001          UNNAMED
2001267N17070    2001          UNNAMED
2001281N18071    2001          UNNAMED
2001288N13084    2001          UNNAMED
2001313N12084    2001          UNNAMED
2001361N01106    2001            VAMEI
2002126N09068    2002          UNNAMED
2002129N08096    2002          UNNAMED
2002295N14082    2002          UNNAMED
2002314N12083    2002          UNNAMED
2002327N10089    2002          UNNAMED
2002355N04077    2002          UNNAMED
2003129N05091    2003          UNNAMED
2003206N21089    2003          UNNAMED
2003240N21089    2003          UNNAMED
2003279N17084    2003          UNNAMED
2003295N09101    2003          UNNAMED
2003315N09067    2003          UNNAMED
2003345N05092    2003          UNNAMED
2004319N10134    2004            MUIFA
2004125N11074    2004          UNNAMED
2004136N15090    2004          UNNAMED
2004162N18068    2004          UNNAMED
2004163N15090    2004          UNNAMED
2004256N23089    2004          UNNAMED
2004274N16069    2004          UNNAMED
2004276N12087    2004          UNNAMED
2004281N23087    2004          UNNAMED
2004307N09068    2004          UNNAMED
2004332N02072    2004          UNNAMED
2005330N09096    2005             BAAZ
2005262N13127    2005           DAMREY
2005338N09093    2005           FANOOS
2005007N04085    2005          UNNAMED
2005012N04090    2005          UNNAMED
2005172N22069    2005          UNNAMED
2005179N22088    2005          UNNAMED
2005210N21088    2005          UNNAMED
2005255N20088    2005          UNNAMED
2005257N20069    2005          UNNAMED
2005260N20091    2005          UNNAMED
2005274N17086    2005          UNNAMED
2005298N12088    2005          UNNAMED
2005324N08085    2005          UNNAMED
2005349N06090    2005          UNNAMED
2005257N15120    2005          VICENTE
2006329N06150    2006           DURIAN
2006114N08090    2006             MALA
2006262N19069    2006            MUKDA
2006012N03081    2006          UNNAMED
2006182N20088    2006          UNNAMED
2006214N20088    2006          UNNAMED
2006224N21088    2006          UNNAMED
2006228N21088    2006          UNNAMED
2006241N20088    2006          UNNAMED
2006247N21089    2006          UNNAMED
2006264N23087    2006          UNNAMED
2006271N18089    2006          UNNAMED
2006300N07078    2006          UNNAMED
2007133N15091    2007            AKASH
2007151N14072    2007             GONU
2007314N10093    2007             SIDR
2007172N15088    2007          UNNAMED
2007178N18089    2007          UNNAMED
2007300N11068    2007          UNNAMED
2008317N11089    2008         KHAI-MUK
2008117N11090    2008           NARGIS
2008329N09082    2008            NISHA
2008298N16085    2008           RASHMI
2008157N16066    2008          UNNAMED
2008168N22090    2008          UNNAMED
2008223N20086    2008          UNNAMED
2008259N20089    2008          UNNAMED
2008293N09060    2008          UNNAMED
2008338N06092    2008          UNNAMED
2009143N17089    2009             AILA
2009104N13088    2009            BIJLI
2009313N11072    2009            PHYAN
2009174N18072    2009          UNNAMED
2009176N23069    2009          UNNAMED
2009201N21089    2009          UNNAMED
2009247N19089    2009          UNNAMED
2009344N06085    2009             WARD
2010136N09057    2010            BANDU
2010293N17093    2010             GIRI
2010305N06105    2010              JAL
2010137N10090    2010            LAILA
2010151N14065    2010             PHET
2010280N17085    2010          UNNAMED
2010286N18090    2010          UNNAMED
2010341N14082    2010          UNNAMED
2011302N13062    2011            KEILA
2011360N09088    2011            THANE
2011033N06083    2011          UNNAMED
2011160N18070    2011          UNNAMED
2011167N22089    2011          UNNAMED
2011203N24085    2011          UNNAMED
2011265N21088    2011          UNNAMED
2011290N15090    2011          UNNAMED
2011310N11066    2011          UNNAMED
2011330N06078    2011          UNNAMED
2012297N11067    2012           MURJAN
2012301N11087    2012            NILAM
2012285N21091    2012          UNNAMED
2012321N14090    2012          UNNAMED
2012357N09064    2012          UNNAMED
2013322N13090    2013            HELEN
2013324N07103    2013            LEHAR
2013339N09084    2013             MADI
2013130N04093    2013   MAHASEN:VIYARU
2013281N12098    2013          PHAILIN
2013149N21090    2013          UNNAMED
2013211N21088    2013          UNNAMED
2013232N22088    2013          UNNAMED
2013305N07141    2013          UNNAMED
2013310N06066    2013          UNNAMED
2014279N11096    2014           HUDHUD
2014159N12068    2014           NANAUK
2014297N11062    2014          NILOFAR
2014003N08086    2014          UNNAMED
2014141N16091    2014          UNNAMED
2014202N22087    2014          UNNAMED
2014216N21089    2014          UNNAMED
2014309N13088    2014          UNNAMED
2015157N13069    2015          ASHOBAA
2015301N11065    2015          CHAPALA
2015207N22091    2015            KOMEN
2015309N14067    2015             MEGH
2015171N18086    2015          UNNAMED
2015173N20067    2015          UNNAMED
2015191N23085    2015          UNNAMED
2015209N26072    2015          UNNAMED
2015216N23081    2015          UNNAMED
2015259N20084    2015          UNNAMED
2015280N13071    2015          UNNAMED
2015312N11084    2015          UNNAMED
2016295N13089    2016            KYANT
2016335N07088    2016             NADA
2016138N10081    2016            ROANU
2016178N22068    2016          UNNAMED
2016222N22089    2016          UNNAMED
2016230N21089    2016          UNNAMED
2016308N13088    2016          UNNAMED
2016341N08092    2016           VARDAH
2017232N19130    2017             HATO
2017104N08085    2017         MAARUTHA
2017147N14087    2017             MORA
2017333N06082    2017            OCKHI
2017163N20090    2017          UNNAMED
2017199N19086    2017          UNNAMED
2017207N24085    2017          UNNAMED
2017282N22088    2017          UNNAMED
2017292N17087    2017          UNNAMED
2017307N07102    2017          UNNAMED
2017319N15083    2017          UNNAMED
2017340N09089    2017          UNNAMED
2018263N17089    2018             DAYE
2018314N12093    2018             GAJA
2018279N11069    2018            LUBAN
2018141N08059    2018           MEKUNU
2018365N08115    2018            PABUK
2018347N07089    2018          PHETHAI
2018136N11054    2018            SAGAR
2018281N14088    2018            TITLI
2018072N05076    2018          UNNAMED
2018148N17090    2018          UNNAMED
2018161N22092    2018          UNNAMED
2018202N21088    2018          UNNAMED
2018219N21088    2018          UNNAMED
2018227N20086    2018          UNNAMED
2018249N22088    2018          UNNAMED
2019302N11118    2019     BULBUL:MATMO
2019116N02090    2019             FANI
2019264N19071    2019      HIKAA:HIKKA
2019296N15066    2019      KYAAR:KYARR
2019301N05081    2019             MAHA
2019335N05058    2019            PAWAN
2019218N21088    2019          UNNAMED
2019273N23070    2019          UNNAMED
2019337N11072    2019          UNNAMED
2019342N09062    2019          UNNAMED
2019160N11073    2019             VAYU
2020136N10088    2020           AMPHAN
2020335N06090    2020           BUREVI
2020326N11063    2020             GATI
2020353N06129    2020          KROVANH
2020153N13072    2020          NISARGA
2020327N08086    2020            NIVAR
2020150N17054    2020          UNNAMED
2020285N15087    2020          UNNAMED
2020291N18069    2020          UNNAMED
2020296N19087    2020          UNNAMED
2021264N13119    2021           DIANMU
2021267N18094    2021 GULAB:SHAHEEN-GU
2021335N08096    2021            JAWAD
2021133N10071    2021          TAUKTAE
2021092N11096    2021          UNNAMED
2021256N20087    2021          UNNAMED
2021280N14068    2021          UNNAMED
2021312N07090    2021          UNNAMED
2021322N11082    2021          UNNAMED
2021143N15090    2021             YAAS
2022126N07095    2022            ASANI
2022338N05100    2022          MANDOUS
2022295N13093    2022          SITRANG
2022062N06085    2022          UNNAMED
2022079N10093    2022          UNNAMED
2022140N16097    2022          UNNAMED
2022197N22069    2022          UNNAMED
2022221N21086    2022          UNNAMED
2022224N22067    2022          UNNAMED
2022226N22088    2022          UNNAMED
2022230N18095    2022          UNNAMED
2022254N20085    2022          UNNAMED
2022324N10086    2022          UNNAMED
2022347N12074    2022          UNNAMED
2022356N09085    2022          UNNAMED
2023156N10067    2023         BIPARJOY
2023293N12089    2023           HAMOON
2023334N08088    2023         MICHAUNG
2023317N10094    2023          MIDHILI
2023129N08091    2023            MOCHA
2023292N11063    2023              TEJ
2023030N08087    2023          UNNAMED
2023160N20092    2023          UNNAMED
2023212N19090    2023          UNNAMED
2023273N16073    2023          UNNAMED
2024238N25077    2024             ASNA
2024295N15092    2024             DANA
2024329N04089    2024           FENGAL
2024145N14087    2024            REMAL
2024201N19086    2024          UNNAMED
2024216N24085    2024          UNNAMED
2024244N18085    2024          UNNAMED
2024252N18087    2024          UNNAMED
2024255N24080    2024          UNNAMED
2024258N22091    2024          UNNAMED
2024288N16065    2024          UNNAMED
2024290N11084    2024          UNNAMED
2024356N14084    2024          UNNAMED
2025266N11137    2025           BUALOI
2025331N06083    2025           DITWAH
2025233N15126    2025           KAJIKI
2025298N11089    2025           MONTHA
2025329N05100    2025           SENYAR
2025275N22068    2025          SHAKHTI
2025144N17073    2025          UNNAMED
2025149N21088    2025          UNNAMED
2025195N23089    2025          UNNAMED
2025196N27075    2025          UNNAMED
2025198N25082    2025          UNNAMED
2025206N21090    2025          UNNAMED
2025231N19085    2025          UNNAMED
2025250N25073    2025          UNNAMED
2025270N19086    2025          UNNAMED
2025274N16087    2025          UNNAMED
2025295N09068    2025          UNNAMED

In [ ]:
# Final North Indian Ocean region
FINAL_NORTH = 30.0
FINAL_SOUTH = 0.0
FINAL_WEST = 40.0
FINAL_EAST = 100.0

final_track = model_track[
    (model_track["LAT"] >= FINAL_SOUTH) &
    (model_track["LAT"] <= FINAL_NORTH) &
    (model_track["LON"] >= FINAL_WEST) &
    (model_track["LON"] <= FINAL_EAST)
].copy()

final_storms = (
    final_track[["SID", "SEASON", "NAME"]]
    .drop_duplicates()
)

print("========== FINAL MODEL REGION ==========")
print("Observations:", len(final_track))
print("Unique cyclones:", final_track["SID"].nunique())
print("Years:", final_track["SEASON"].min(), "to", final_track["SEASON"].max())

print("\nCoordinates:")
print("Latitude :", final_track["LAT"].min(), "to", final_track["LAT"].max())
print("Longitude:", final_track["LON"].min(), "to", final_track["LON"].max())

print("\nMissing labels:")
print(final_track[["USA_WIND", "USA_PRES"]].isna().sum())

print("\nStorms by year:")
print(
    final_storms.groupby("SEASON")
    .size()
    .to_string()
)

========== FINAL MODEL REGION ==========
Observations: 8817
Unique cyclones: 264
Years: 2000 to 2025

Coordinates:
Latitude : 0.7 to 29.2
Longitude: 41.8 to 100.0

Missing labels:
USA_WIND    2335
USA_PRES    2529
dtype: int64

Storms by year:
SEASON
2000     6
2001     7
2002     6
2003     7
2004    11
2005    16
2006    13
2007     6
2008    10
2009     8
2010     8
2011    10
2012     5
2013    10
2014     8
2015    12
2016     8
2017    12
2018    15
2019    11
2020    10
2021    10
2022    15
2023    10
2024    13
2025    17

In [ ]:
final_track.to_csv(
    "final_NI_cyclone_tracks_2000_2025.csv",
    index=False
)

print("Saved:", len(final_track), "observations")

Saved: 8817 observations

In [ ]:
print("Earliest observation:")
print(final_track["ISO_TIME"].min())

print("\nLatest observation:")
print(final_track["ISO_TIME"].max())

Earliest observation:
2000-03-27 12:00:00

Latest observation:
2025-12-02 18:00:00

In [ ]:
time_counts = (
    final_track["ISO_TIME"]
    .dt.hour
    .value_counts()
    .sort_index()
)

print("IBTrACS observation hours:")
print(time_counts)

IBTrACS observation hours:
ISO_TIME
0     1114
3     1109
6     1137
9     1085
12    1117
14       1
15    1077
18    1113
21    1064
Name: count, dtype: int64

In [ ]:
# Analyze cyclone observations by month

monthly_counts = (
    final_track
    .groupby(final_track["ISO_TIME"].dt.month)
    .size()
)

month_names = {
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December"
}

print("========== OBSERVATIONS BY MONTH ==========")

for month, count in monthly_counts.sort_index().items():
    print(f"{month_names[month]:>10}: {count}")

========== OBSERVATIONS BY MONTH ==========
   January: 227
  February: 17
     March: 95
     April: 199
       May: 1144
      June: 830
      July: 377
    August: 495
 September: 714
   October: 1681
  November: 1742
  December: 1296

In [ ]:
# Analyze cyclone counts by month

monthly_storms = (
    final_track[["SID", "ISO_TIME"]]
    .drop_duplicates("SID")
    .assign(MONTH=lambda x: x["ISO_TIME"].dt.month)
    .groupby("MONTH")
    .size()
)

print("\n========== CYCLONES BY MONTH ==========")

for month, count in monthly_storms.sort_index().items():
    print(f"{month_names[month]:>10}: {count}")

========== CYCLONES BY MONTH ==========
   January: 6
  February: 1
     March: 4
     April: 6
       May: 31
      June: 24
      July: 19
    August: 25
 September: 31
   October: 49
  November: 45
  December: 23

In [ ]:
# Create one row per cyclone with its start/end time and spatial extent

storm_ranges = (
    final_track
    .groupby(["SID", "SEASON", "NAME"])
    .agg(
        start_time=("ISO_TIME", "min"),
        end_time=("ISO_TIME", "max"),
        min_lat=("LAT", "min"),
        max_lat=("LAT", "max"),
        min_lon=("LON", "min"),
        max_lon=("LON", "max"),
        observations=("ISO_TIME", "count")
    )
    .reset_index()
)

print("Number of cyclones:", len(storm_ranges))
print("\nFirst 20 cyclones:")
print(storm_ranges.head(20).to_string(index=False))

Number of cyclones: 264

First 20 cyclones:
          SID  SEASON    NAME          start_time            end_time  min_lat  max_lat  min_lon  max_lon  observations
2000088N08090    2000 UNNAMED 2000-03-27 12:00:00 2000-03-30 12:00:00      7.5     16.0     88.0     90.5            25
2000236N17084    2000 UNNAMED 2000-08-23 03:00:00 2000-08-24 00:00:00     16.4     18.0     79.5     83.5             8
2000289N15089    2000 UNNAMED 2000-10-14 18:00:00 2000-10-19 06:00:00     14.0     14.7     82.0     89.0            37
2000299N13093    2000 UNNAMED 2000-10-25 09:00:00 2000-10-29 00:00:00     13.5     24.0     88.1     94.0            30
2000331N09092    2000 UNNAMED 2000-11-26 03:00:00 2000-12-06 00:00:00      8.0     11.9     54.5     91.5            80
2000358N08086    2000 UNNAMED 2000-12-23 03:00:00 2000-12-29 00:00:00      7.8      9.2     75.5     86.0            48
2001141N14068    2001 UNNAMED 2001-05-21 06:00:00 2001-05-29 12:00:00     13.6     23.4     67.5     71.6            67
2001163N20087    2001 UNNAMED 2001-06-12 03:00:00 2001-06-13 12:00:00     19.5     21.5     84.5     87.0            12
2001267N17070    2001 UNNAMED 2001-09-24 00:00:00 2001-09-28 12:00:00     16.6     19.4     61.1     69.8            37
2001281N18071    2001 UNNAMED 2001-10-08 06:00:00 2001-10-13 06:00:00     17.7     20.0     65.0     70.8            41
2001288N13084    2001 UNNAMED 2001-10-14 12:00:00 2001-10-16 18:00:00     13.5     15.0     79.0     84.0            19
2001313N12084    2001 UNNAMED 2001-11-09 00:00:00 2001-11-12 06:00:00     12.0     17.3     82.1     85.7            27
2001361N01106    2001   VAMEI 2001-12-28 18:00:00 2002-01-01 06:00:00      2.0      4.6     89.3     99.9            29
2002126N09068    2002 UNNAMED 2002-05-05 18:00:00 2002-05-10 18:00:00      8.6     17.4     53.1     67.7            41
2002129N08096    2002 UNNAMED 2002-05-09 06:00:00 2002-05-12 12:00:00      8.4     19.2     95.1     97.4            27
2002295N14082    2002 UNNAMED 2002-10-22 09:00:00 2002-10-23 18:00:00     13.5     14.1     81.5     81.5            12
2002314N12083    2002 UNNAMED 2002-11-09 18:00:00 2002-11-12 15:00:00     11.7     25.0     82.5     91.5            24
2002327N10089    2002 UNNAMED 2002-11-22 18:00:00 2002-11-28 12:00:00      9.5     18.0     87.8     92.0            47
2002355N04077    2002 UNNAMED 2002-12-21 03:00:00 2002-12-25 18:00:00      1.9      8.2     77.0     86.7            38
2003129N05091    2003 UNNAMED 2003-05-08 12:00:00 2003-05-19 21:00:00      4.2     20.0     85.4     94.5            92

In [ ]:
print("\n========== OVERALL STORM EXTENT ==========")

print("Earliest storm:", storm_ranges["start_time"].min())
print("Latest storm:", storm_ranges["end_time"].max())

print("Minimum latitude:", storm_ranges["min_lat"].min())
print("Maximum latitude:", storm_ranges["max_lat"].max())

print("Minimum longitude:", storm_ranges["min_lon"].min())
print("Maximum longitude:", storm_ranges["max_lon"].max())

========== OVERALL STORM EXTENT ==========
Earliest storm: 2000-03-27 12:00:00
Latest storm: 2025-12-02 18:00:00
Minimum latitude: 0.7
Maximum latitude: 29.2
Minimum longitude: 41.8
Maximum longitude: 100.0

In [ ]:
# ============================================
# ERA5 DATA REQUIREMENT ANALYSIS
# ============================================

# Work only with observations that have valid time/location
era5_needed = final_track.dropna(
    subset=["ISO_TIME", "LAT", "LON"]
).copy()

# ERA5 is hourly, so round each observation to its hour
era5_needed["ERA5_TIME"] = era5_needed["ISO_TIME"].dt.floor("h")

# Number of unique time points
unique_times = era5_needed["ERA5_TIME"].nunique()

# Number of unique cyclone/time combinations
unique_storm_times = era5_needed[
    ["SID", "ERA5_TIME"]
].drop_duplicates().shape[0]

print("========== ERA5 REQUIREMENT ==========")

print("IBTrACS observations:", len(era5_needed))
print("Unique ERA5 timestamps:", unique_times)
print("Unique cyclone-time pairs:", unique_storm_times)

print("\nERA5 time range:")
print(era5_needed["ERA5_TIME"].min())
print("to")
print(era5_needed["ERA5_TIME"].max())

print("\nSpatial range:")
print("Latitude :", era5_needed["LAT"].min(), "to", era5_needed["LAT"].max())
print("Longitude:", era5_needed["LON"].min(), "to", era5_needed["LON"].max())

# Count observations per year
year_counts = (
    era5_needed
    .groupby(era5_needed["ERA5_TIME"].dt.year)
    .size()
)

print("\nObservations requiring ERA5 by year:")
print(year_counts.to_string())

========== ERA5 REQUIREMENT ==========
IBTrACS observations: 8817
Unique ERA5 timestamps: 8217
Unique cyclone-time pairs: 8817

ERA5 time range:
2000-03-27 12:00:00
to
2025-12-02 18:00:00

Spatial range:
Latitude : 0.7 to 29.2
Longitude: 41.8 to 100.0

Observations requiring ERA5 by year:
ERA5_TIME
2000    228
2001    229
2002    192
2003    292
2004    406
2005    544
2006    389
2007    236
2008    328
2009    173
2010    296
2011    316
2012    161
2013    490
2014    335
2015    383
2016    350
2017    211
2018    423
2019    641
2020    283
2021    301
2022    413
2023    418
2024    402
2025    377

In [ ]:
# ============================================
# APPROXIMATE ERA5 GRID POINTS
# ============================================

# ERA5 atmospheric grid spacing = 0.25 degrees

era5_needed["ERA5_LAT"] = (
    np.round(era5_needed["LAT"] / 0.25) * 0.25
)

era5_needed["ERA5_LON"] = (
    np.round(era5_needed["LON"] / 0.25) * 0.25
)

unique_grid_points = era5_needed[
    ["ERA5_LAT", "ERA5_LON"]
].drop_duplicates()

print("========== ERA5 GRID ==========")

print(
    "Unique approximate ERA5 grid points:",
    len(unique_grid_points)
)

print(
    "Latitude grid range:",
    unique_grid_points["ERA5_LAT"].min(),
    "to",
    unique_grid_points["ERA5_LAT"].max()
)

print(
    "Longitude grid range:",
    unique_grid_points["ERA5_LON"].min(),
    "to",
    unique_grid_points["ERA5_LON"].max()
)

========== ERA5 GRID ==========
Unique approximate ERA5 grid points: 5264
Latitude grid range: 0.75 to 29.25
Longitude grid range: 41.75 to 100.0

In [ ]:
# ============================================
# CREATE ERA5 LOOKUP TABLE
# ============================================

era5_lookup = final_track[
    ["SID", "SEASON", "NAME", "ISO_TIME",
     "LAT", "LON", "USA_WIND", "USA_PRES"]
].copy()

# ERA5 is on a 0.25° grid.
# This is only a preliminary grid estimate.
era5_lookup["ERA5_LAT"] = (
    np.round(era5_lookup["LAT"] / 0.25) * 0.25
)

era5_lookup["ERA5_LON"] = (
    np.round(era5_lookup["LON"] / 0.25) * 0.25
)

# ERA5 time corresponding to each IBTrACS observation
era5_lookup["ERA5_TIME"] = (
    era5_lookup["ISO_TIME"].dt.floor("h")
)

print("ERA5 lookup table created!")
print("Rows:", len(era5_lookup))

print("\nFirst 10 rows:")
print(
    era5_lookup.head(10).to_string(index=False)
)

ERA5 lookup table created!
Rows: 8817

First 10 rows:
          SID  SEASON    NAME            ISO_TIME  LAT  LON  USA_WIND  USA_PRES  ERA5_LAT  ERA5_LON           ERA5_TIME
2000088N08090    2000 UNNAMED 2000-03-27 12:00:00  7.5 90.0       NaN       NaN      7.50     90.00 2000-03-27 12:00:00
2000088N08090    2000 UNNAMED 2000-03-27 15:00:00  8.0 89.4       NaN       NaN      8.00     89.50 2000-03-27 15:00:00
2000088N08090    2000 UNNAMED 2000-03-27 18:00:00  8.5 89.0       NaN       NaN      8.50     89.00 2000-03-27 18:00:00
2000088N08090    2000 UNNAMED 2000-03-27 21:00:00  9.0 89.0       NaN       NaN      9.00     89.00 2000-03-27 21:00:00
2000088N08090    2000 UNNAMED 2000-03-28 00:00:00  9.5 89.0       NaN       NaN      9.50     89.00 2000-03-28 00:00:00
2000088N08090    2000 UNNAMED 2000-03-28 03:00:00 10.0 88.5       NaN       NaN     10.00     88.50 2000-03-28 03:00:00
2000088N08090    2000 UNNAMED 2000-03-28 06:00:00 10.7 88.2       NaN       NaN     10.75     88.25 2000-03-28 06:00:00
2000088N08090    2000 UNNAMED 2000-03-28 09:00:00 11.5 88.0       NaN       NaN     11.50     88.00 2000-03-28 09:00:00
2000088N08090    2000 UNNAMED 2000-03-28 12:00:00 12.0 88.0       NaN       NaN     12.00     88.00 2000-03-28 12:00:00
2000088N08090    2000 UNNAMED 2000-03-28 15:00:00 12.0 88.0       NaN       NaN     12.00     88.00 2000-03-28 15:00:00

In [ ]:
# ============================================
# UNIQUE ERA5 REQUEST COMBINATIONS
# ============================================

unique_requests = (
    era5_lookup[
        ["ERA5_TIME", "ERA5_LAT", "ERA5_LON"]
    ]
    .drop_duplicates()
    .sort_values(
        ["ERA5_TIME", "ERA5_LAT", "ERA5_LON"]
    )
    .reset_index(drop=True)
)

print("========================================")
print("UNIQUE ERA5 TIME + LOCATION COMBINATIONS")
print("========================================")

print("Total unique combinations:",
      len(unique_requests))

print("\nFirst 20:")
print(
    unique_requests.head(20).to_string(index=False)
)

========================================
UNIQUE ERA5 TIME + LOCATION COMBINATIONS
========================================
Total unique combinations: 8817

First 20:
          ERA5_TIME  ERA5_LAT  ERA5_LON
2000-03-27 12:00:00      7.50     90.00
2000-03-27 15:00:00      8.00     89.50
2000-03-27 18:00:00      8.50     89.00
2000-03-27 21:00:00      9.00     89.00
2000-03-28 00:00:00      9.50     89.00
2000-03-28 03:00:00     10.00     88.50
2000-03-28 06:00:00     10.75     88.25
2000-03-28 09:00:00     11.50     88.00
2000-03-28 12:00:00     12.00     88.00
2000-03-28 15:00:00     12.00     88.00
2000-03-28 18:00:00     12.00     88.00
2000-03-28 21:00:00     12.25     88.00
2000-03-29 00:00:00     12.50     88.00
2000-03-29 03:00:00     13.00     88.00
2000-03-29 06:00:00     13.50     88.00
2000-03-29 09:00:00     13.75     88.25
2000-03-29 12:00:00     14.00     88.50
2000-03-29 15:00:00     14.50     89.00
2000-03-29 18:00:00     15.00     89.50
2000-03-29 21:00:00     15.00     89.50

In [ ]:
!pip -q install xarray zarr fsspec gcsfs

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.7/363.7 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 53.1 MB/s eta 0:00:00

In [ ]:
import getpass

CDS_API_KEY = getpass.getpass("Enter your CDS API key: ")

print("API key received:", "Yes" if CDS_API_KEY else "No")

Enter your CDS API key: ··········
API key received: Yes

In [ ]:
import xarray as xr

surface_geo_url = (
    "https://arco.datastores.ecmwf.int/"
    "cadl-arco-geo-002/arco/"
    "reanalysis_era5_single_levels/sfc/"
    "geoChunked.zarr"
)

ds = xr.open_zarr(
    surface_geo_url,
    consolidated=True,
    storage_options={
        "headers": {
            "Authorization": f"Bearer {CDS_API_KEY}"
        }
    }
)

print(ds)

<xarray.Dataset> Size: 63TB
Dimensions:    (time: 759960, latitude: 721, longitude: 1440)
Coordinates:
  * time       (time) datetime64[ns] 6MB 1940-01-01 ... 2026-09-10T23:00:00
  * latitude   (latitude) float64 6kB -90.0 -89.75 -89.5 ... 89.5 89.75 90.0
  * longitude  (longitude) float64 12kB -180.0 -179.8 -179.5 ... 179.5 179.8
Data variables: (12/20)
    blh        (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    cbh        (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    d2m        (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    fdir       (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    fg10       (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    msl        (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    ...         ...
    tcc        (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    tp         (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    u10        (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    u100       (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    v10        (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    v100       (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
Attributes:
    Conventions:             CF-1.7
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_edition:            1
    GRIB_subCentre:          0
    history:                 2024-09-02T04:48 GRIB to CDM+CF via cfgrib-0.9.1...
    institution:             European Centre for Medium-Range Weather Forecasts

In [ ]:
required_vars = [
    "u10",
    "v10",
    "t2m",
    "d2m",
    "msl",
    "sst"
]

available = [v for v in required_vars if v in ds.data_vars]
missing = [v for v in required_vars if v not in ds.data_vars]

print("Available:", available)
print("Missing:", missing)

Available: ['u10', 'v10', 't2m', 'd2m', 'msl', 'sst']
Missing: []

In [ ]:
print("ERA5 latitude:")
print(ds.latitude.values[:5])
print("...")

print("\nERA5 longitude:")
print(ds.longitude.values[:5])
print("...")

print("\nERA5 time:")
print(ds.time.values[:5])
print("...")

ERA5 latitude:
[-90.   -89.75 -89.5  -89.25 -89.  ]
...

ERA5 longitude:
[-180.   -179.75 -179.5  -179.25 -179.  ]
...

ERA5 time:
['1940-01-01T00:00:00.000000000' '1940-01-01T01:00:00.000000000'
 '1940-01-01T02:00:00.000000000' '1940-01-01T03:00:00.000000000'
 '1940-01-01T04:00:00.000000000']
...

In [ ]:
print("IBTrACS lookup:")
display(era5_lookup.head())

print("\nERA5 dataset:")
print(ds)

IBTrACS lookup:

,SID,SEASON,NAME,ISO_TIME,LAT,LON,USA_WIND,USA_PRES,ERA5_LAT,ERA5_LON,ERA5_TIME
53226,2000088N08090,2000,UNNAMED,2000-03-27 12:00:00,7.5,90.0,NaN,NaN,7.5,90.0,2000-03-27 12:00:00
53227,2000088N08090,2000,UNNAMED,2000-03-27 15:00:00,8.0,89.4,NaN,NaN,8.0,89.5,2000-03-27 15:00:00
53228,2000088N08090,2000,UNNAMED,2000-03-27 18:00:00,8.5,89.0,NaN,NaN,8.5,89.0,2000-03-27 18:00:00
53229,2000088N08090,2000,UNNAMED,2000-03-27 21:00:00,9.0,89.0,NaN,NaN,9.0,89.0,2000-03-27 21:00:00
53230,2000088N08090,2000,UNNAMED,2000-03-28 00:00:00,9.5,89.0,NaN,NaN,9.5,89.0,2000-03-28 00:00:00

ERA5 dataset:
<xarray.Dataset> Size: 63TB
Dimensions:    (time: 759960, latitude: 721, longitude: 1440)
Coordinates:
  * time       (time) datetime64[ns] 6MB 1940-01-01 ... 2026-09-10T23:00:00
  * latitude   (latitude) float64 6kB -90.0 -89.75 -89.5 ... 89.5 89.75 90.0
  * longitude  (longitude) float64 12kB -180.0 -179.8 -179.5 ... 179.5 179.8
Data variables: (12/20)
    blh        (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    cbh        (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    d2m        (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    fdir       (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    fg10       (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    msl        (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    ...         ...
    tcc        (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    tp         (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    u10        (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    u100       (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    v10        (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
    v100       (time, latitude, longitude) float32 3TB dask.array<chunksize=(67584, 4, 4), meta=np.ndarray>
Attributes:
    Conventions:             CF-1.7
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_edition:            1
    GRIB_subCentre:          0
    history:                 2024-09-02T04:48 GRIB to CDM+CF via cfgrib-0.9.1...
    institution:             European Centre for Medium-Range Weather Forecasts

In [ ]:
# ============================================
# STEP: Extract ERA5 data for cyclone points
# ============================================

import numpy as np
import pandas as pd

# Make a copy so our original dataset stays safe
merged_track = era5_lookup.copy()

# Convert coordinates/time to the exact types expected by xarray
times = pd.to_datetime(merged_track["ERA5_TIME"]).values
lats = merged_track["LAT"].values
lons = merged_track["LON"].values

print("Number of cyclone observations:", len(merged_track))

Number of cyclone observations: 8817

In [ ]:
# ============================================
# Extract ERA5 variables
# ============================================

era5_points = ds[
    ["u10", "v10", "t2m", "d2m", "msl", "sst"]
].sel(
    time=xr.DataArray(times, dims="points"),
    latitude=xr.DataArray(lats, dims="points"),
    longitude=xr.DataArray(lons, dims="points"),
    method="nearest"
)

print(era5_points)

<xarray.Dataset> Size: 423kB
Dimensions:    (points: 8817)
Coordinates:
    latitude   (points) float64 71kB 7.5 8.0 8.5 9.0 ... 12.25 12.25 12.25 12.0
    longitude  (points) float64 71kB 90.0 89.5 89.0 89.0 ... 80.5 80.25 80.25
    time       (points) datetime64[ns] 71kB 2000-03-27T12:00:00 ... 2025-12-0...
Dimensions without coordinates: points
Data variables:
    u10        (points) float32 35kB dask.array<chunksize=(8817,), meta=np.ndarray>
    v10        (points) float32 35kB dask.array<chunksize=(8817,), meta=np.ndarray>
    t2m        (points) float32 35kB dask.array<chunksize=(8817,), meta=np.ndarray>
    d2m        (points) float32 35kB dask.array<chunksize=(8817,), meta=np.ndarray>
    msl        (points) float32 35kB dask.array<chunksize=(8817,), meta=np.ndarray>
    sst        (points) float32 35kB dask.array<chunksize=(8817,), meta=np.ndarray>
Attributes:
    Conventions:             CF-1.7
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_edition:            1
    GRIB_subCentre:          0
    history:                 2024-09-02T04:48 GRIB to CDM+CF via cfgrib-0.9.1...
    institution:             European Centre for Medium-Range Weather Forecasts

In [ ]:
print("Extraction complete!")

Extraction complete!

In [ ]:
# ============================================
# STEP 3 — Load the selected ERA5 points
# ============================================

print("Loading selected ERA5 values...")

era5_points = era5_points.compute()

print("ERA5 values loaded successfully!")
print(era5_points)

Loading selected ERA5 values...

KeyboardInterrupt:

In [ ]:
# Remove the slow lazy extraction object
del era5_points

print("Ready for batch extraction.")

Ready for batch extraction.

In [ ]:
# ============================================
# CHECK UNIQUE ERA5 GRID LOCATIONS
# ============================================

location_counts = (
    era5_lookup[["ERA5_LAT", "ERA5_LON"]]
    .drop_duplicates()
)

print("Total cyclone observations:", len(era5_lookup))
print("Unique ERA5 grid locations:", len(location_counts))

display(location_counts.head(20))

Total cyclone observations: 8817
Unique ERA5 grid locations: 5264

       ERA5_LAT  ERA5_LON
53226      7.50     90.00
53227      8.00     89.50
53228      8.50     89.00
53229      9.00     89.00
53230      9.50     89.00
53231     10.00     88.50
53232     10.75     88.25
53233     11.50     88.00
53234     12.00     88.00
53237     12.25     88.00
53238     12.50     88.00
53239     13.00     88.00
53240     13.50     88.00
53241     13.75     88.25
53242     14.00     88.50
53243     14.50     89.00
53244     15.00     89.50
53247     15.50     90.00
53249     15.00     90.00
53250     16.00     90.50

In [ ]:
# How many observations are represented by each grid location?

location_frequency = (
    era5_lookup
    .groupby(["ERA5_LAT", "ERA5_LON"])
    .size()
    .sort_values(ascending=False)
)

print("Most frequently used ERA5 grid locations:")
display(location_frequency.head(20))

Most frequently used ERA5 grid locations:

ERA5_LAT  ERA5_LON
24.5      80.5        27
22.0      90.5        16
13.0      85.5        15
23.0      88.0        15
22.5      88.0        15
18.0      66.0        14
20.5      87.5        13
23.5      85.5        12
20.5      88.0        12
23.5      86.0        12
14.0      81.5        12
24.0      85.0        12
19.5      85.5        11
23.0      86.0        11
20.5      68.0        11
23.0      86.5        10
21.5      87.5        10
          64.0         9
23.0      80.0         9
22.5      89.0         9
dtype: int64

In [ ]:
# ============================================
# CONNECT TO TIME-CHUNKED ERA5 ARCO
# ============================================

surface_time_url = (
    "https://arco.datastores.ecmwf.int/"
    "cadl-arco-time-002/arco/"
    "reanalysis_era5_single_levels/sfc/"
    "timeChunked.zarr"
)

ds_time = xr.open_zarr(
    surface_time_url,
    consolidated=True,
    storage_options={
        "headers": {
            "Authorization": f"Bearer {CDS_API_KEY}"
        }
    }
)

print(ds_time)

<xarray.Dataset> Size: 63TB
Dimensions:    (time: 759960, latitude: 721, longitude: 1440)
Coordinates:
  * time       (time) datetime64[ns] 6MB 1940-01-01 ... 2026-09-10T23:00:00
  * latitude   (latitude) float64 6kB -90.0 -89.75 -89.5 ... 89.5 89.75 90.0
  * longitude  (longitude) float64 12kB -180.0 -179.8 -179.5 ... 179.5 179.8
Data variables: (12/20)
    blh        (time, latitude, longitude) float32 3TB dask.array<chunksize=(1, 721, 1024), meta=np.ndarray>
    cbh        (time, latitude, longitude) float32 3TB dask.array<chunksize=(1, 721, 1024), meta=np.ndarray>
    d2m        (time, latitude, longitude) float32 3TB dask.array<chunksize=(1, 721, 1024), meta=np.ndarray>
    fdir       (time, latitude, longitude) float32 3TB dask.array<chunksize=(1, 721, 1024), meta=np.ndarray>
    fg10       (time, latitude, longitude) float32 3TB dask.array<chunksize=(1, 721, 1024), meta=np.ndarray>
    msl        (time, latitude, longitude) float32 3TB dask.array<chunksize=(1, 721, 1024), meta=np.ndarray>
    ...         ...
    tcc        (time, latitude, longitude) float32 3TB dask.array<chunksize=(1, 721, 1024), meta=np.ndarray>
    tp         (time, latitude, longitude) float32 3TB dask.array<chunksize=(1, 721, 1024), meta=np.ndarray>
    u10        (time, latitude, longitude) float32 3TB dask.array<chunksize=(1, 721, 1024), meta=np.ndarray>
    u100       (time, latitude, longitude) float32 3TB dask.array<chunksize=(1, 721, 1024), meta=np.ndarray>
    v10        (time, latitude, longitude) float32 3TB dask.array<chunksize=(1, 721, 1024), meta=np.ndarray>
    v100       (time, latitude, longitude) float32 3TB dask.array<chunksize=(1, 721, 1024), meta=np.ndarray>
Attributes:
    Conventions:             CF-1.7
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_edition:            1
    GRIB_subCentre:          0
    history:                 2024-09-02T04:48 GRIB to CDM+CF via cfgrib-0.9.1...
    institution:             European Centre for Medium-Range Weather Forecasts

In [ ]:
required_vars = ["u10", "v10", "t2m", "d2m", "msl", "sst"]

print("Available:")
print([v for v in required_vars if v in ds_time.data_vars])

print("\nMissing:")
print([v for v in required_vars if v not in ds_time.data_vars])

Available:
['u10', 'v10', 't2m', 'd2m', 'msl', 'sst']

Missing:
[]

In [ ]:
# ============================================
# TEST: Retrieve one ERA5 time step
# ============================================

test_time = pd.Timestamp("2000-03-27 12:00:00")

test_era5 = ds_time[
    ["u10", "v10", "t2m", "d2m", "msl", "sst"]
].sel(
    time=test_time,
    latitude=slice(30, 0),
    longitude=slice(40, 100)
)

print(test_era5)

<xarray.Dataset> Size: 2kB
Dimensions:    (latitude: 0, longitude: 241)
Coordinates:
  * latitude   (latitude) float64 0B
  * longitude  (longitude) float64 2kB 40.0 40.25 40.5 ... 99.5 99.75 100.0
    time       datetime64[ns] 8B 2000-03-27T12:00:00
Data variables:
    u10        (latitude, longitude) float32 0B dask.array<chunksize=(0, 144), meta=np.ndarray>
    v10        (latitude, longitude) float32 0B dask.array<chunksize=(0, 144), meta=np.ndarray>
    t2m        (latitude, longitude) float32 0B dask.array<chunksize=(0, 144), meta=np.ndarray>
    d2m        (latitude, longitude) float32 0B dask.array<chunksize=(0, 144), meta=np.ndarray>
    msl        (latitude, longitude) float32 0B dask.array<chunksize=(0, 144), meta=np.ndarray>
    sst        (latitude, longitude) float32 0B dask.array<chunksize=(0, 144), meta=np.ndarray>
Attributes:
    Conventions:             CF-1.7
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_edition:            1
    GRIB_subCentre:          0
    history:                 2024-09-02T04:48 GRIB to CDM+CF via cfgrib-0.9.1...
    institution:             European Centre for Medium-Range Weather Forecasts

In [ ]:
test_loaded = test_era5.compute()

print("Loaded successfully!")
print(test_loaded)

Loaded successfully!
<xarray.Dataset> Size: 2kB
Dimensions:    (latitude: 0, longitude: 241)
Coordinates:
  * latitude   (latitude) float64 0B
  * longitude  (longitude) float64 2kB 40.0 40.25 40.5 ... 99.5 99.75 100.0
    time       datetime64[ns] 8B 2000-03-27T12:00:00
Data variables:
    u10        (latitude, longitude) float32 0B
    v10        (latitude, longitude) float32 0B
    t2m        (latitude, longitude) float32 0B
    d2m        (latitude, longitude) float32 0B
    msl        (latitude, longitude) float32 0B
    sst        (latitude, longitude) float32 0B
Attributes:
    Conventions:             CF-1.7
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_edition:            1
    GRIB_subCentre:          0
    history:                 2024-09-02T04:48 GRIB to CDM+CF via cfgrib-0.9.1...
    institution:             European Centre for Medium-Range Weather Forecasts

In [ ]:
# ============================================
# TEST: Extract first 10 cyclone observations
# ============================================

test_rows = era5_lookup.head(10).copy()

results = []

for _, row in test_rows.iterrows():

    era5_hour = ds_time[
        ["u10", "v10", "t2m", "d2m", "msl", "sst"]
    ].sel(
        time=row["ERA5_TIME"],
        latitude=row["LAT"],
        longitude=row["LON"],
        method="nearest"
    ).compute()

    results.append({
        "SID": row["SID"],
        "NAME": row["NAME"],
        "ISO_TIME": row["ISO_TIME"],
        "LAT": row["LAT"],
        "LON": row["LON"],
        "u10": float(era5_hour["u10"].values),
        "v10": float(era5_hour["v10"].values),
        "t2m": float(era5_hour["t2m"].values),
        "d2m": float(era5_hour["d2m"].values),
        "msl": float(era5_hour["msl"].values),
        "sst": float(era5_hour["sst"].values)
    })

test_result = pd.DataFrame(results)

display(test_result)

,SID,NAME,ISO_TIME,LAT,LON,u10,v10,t2m,d2m,msl,sst
0,2000088N08090,UNNAMED,2000-03-27 12:00:00,7.5,90.0,1.450592,5.896347,299.326416,296.274719,100710.6250,302.366211
1,2000088N08090,UNNAMED,2000-03-27 15:00:00,8.0,89.4,2.002869,5.346909,299.936035,296.399353,100874.2500,302.217773
2,2000088N08090,UNNAMED,2000-03-27 18:00:00,8.5,89.0,2.830093,2.947983,299.573486,296.321960,100803.4375,302.290039
3,2000088N08090,UNNAMED,2000-03-27 21:00:00,9.0,89.0,1.855988,2.882126,298.813660,296.394775,100564.2500,302.408203
4,2000088N08090,UNNAMED,2000-03-28 00:00:00,9.5,89.0,-1.126343,2.953934,298.258209,295.986389,100716.8750,302.231445
5,2000088N08090,UNNAMED,2000-03-28 03:00:00,10.0,88.5,-3.732239,3.859818,299.005005,296.318970,100918.9375,302.144531
6,2000088N08090,UNNAMED,2000-03-28 06:00:00,10.7,88.2,-3.247101,4.085251,299.129211,296.424316,100803.6875,301.921875
7,2000088N08090,UNNAMED,2000-03-28 09:00:00,11.5,88.0,-4.576019,0.697449,298.538940,296.084412,100614.6875,302.132812
8,2000088N08090,UNNAMED,2000-03-28 12:00:00,12.0,88.0,-4.973770,1.032089,298.535034,296.560852,100644.6875,302.291992
9,2000088N08090,UNNAMED,2000-03-28 15:00:00,12.0,88.0,-4.982727,0.707001,299.470001,296.398682,100827.0625,302.291992

In [ ]:
# ============================================
# CHECK UNIQUE CYCLONE HOURS
# ============================================

unique_hours = era5_lookup["ERA5_TIME"].drop_duplicates().sort_values()

print("Total observations:", len(era5_lookup))
print("Unique ERA5 hours:", len(unique_hours))

display(unique_hours.head(20))

Total observations: 8817
Unique ERA5 hours: 8217

53226   2000-03-27 12:00:00
53227   2000-03-27 15:00:00
53228   2000-03-27 18:00:00
53229   2000-03-27 21:00:00
53230   2000-03-28 00:00:00
53231   2000-03-28 03:00:00
53232   2000-03-28 06:00:00
53233   2000-03-28 09:00:00
53234   2000-03-28 12:00:00
53235   2000-03-28 15:00:00
53236   2000-03-28 18:00:00
53237   2000-03-28 21:00:00
53238   2000-03-29 00:00:00
53239   2000-03-29 03:00:00
53240   2000-03-29 06:00:00
53241   2000-03-29 09:00:00
53242   2000-03-29 12:00:00
53243   2000-03-29 15:00:00
53244   2000-03-29 18:00:00
53245   2000-03-29 21:00:00
Name: ERA5_TIME, dtype: datetime64[ns]

In [ ]:
# ============================================
# INSPECT CYCLONE RANGES
# ============================================

display(
    storm_ranges[
        ["SID", "SEASON", "NAME",
         "START_TIME", "END_TIME",
         "MIN_LAT", "MAX_LAT",
         "MIN_LON", "MAX_LON",
         "OBSERVATIONS"]
    ].head(10)
)

KeyError: "['START_TIME', 'END_TIME', 'MIN_LAT', 'MAX_LAT', 'MIN_LON', 'MAX_LON', 'OBSERVATIONS'] not in index"

In [ ]:
# Check the actual columns in storm_ranges

print("storm_ranges columns:")
print(storm_ranges.columns.tolist())

print("\nFirst 5 rows:")
display(storm_ranges.head())

storm_ranges columns:
['SID', 'SEASON', 'NAME', 'start_time', 'end_time', 'min_lat', 'max_lat', 'min_lon', 'max_lon', 'observations']

First 5 rows:

,SID,SEASON,NAME,start_time,end_time,min_lat,max_lat,min_lon,max_lon,observations
0,2000088N08090,2000,UNNAMED,2000-03-27 12:00:00,2000-03-30 12:00:00,7.5,16.0,88.0,90.5,25
1,2000236N17084,2000,UNNAMED,2000-08-23 03:00:00,2000-08-24 00:00:00,16.4,18.0,79.5,83.5,8
2,2000289N15089,2000,UNNAMED,2000-10-14 18:00:00,2000-10-19 06:00:00,14.0,14.7,82.0,89.0,37
3,2000299N13093,2000,UNNAMED,2000-10-25 09:00:00,2000-10-29 00:00:00,13.5,24.0,88.1,94.0,30
4,2000331N09092,2000,UNNAMED,2000-11-26 03:00:00,2000-12-06 00:00:00,8.0,11.9,54.5,91.5,80

In [ ]:
# ============================================
# CYCLONE RANGE SUMMARY
# ============================================

storm_ranges["duration_hours"] = (
    storm_ranges["end_time"] -
    storm_ranges["start_time"]
).dt.total_seconds() / 3600

storm_ranges["lat_span"] = (
    storm_ranges["max_lat"] -
    storm_ranges["min_lat"]
)

storm_ranges["lon_span"] = (
    storm_ranges["max_lon"] -
    storm_ranges["min_lon"]
)

print("Number of cyclones:", len(storm_ranges))

print(
    "Median duration:",
    round(storm_ranges["duration_hours"].median(), 1),
    "hours"
)

print(
    "Median latitude span:",
    round(storm_ranges["lat_span"].median(), 2),
    "degrees"
)

print(
    "Median longitude span:",
    round(storm_ranges["lon_span"].median(), 2),
    "degrees"
)

print("\nSummary:")
display(
    storm_ranges[
        [
            "duration_hours",
            "lat_span",
            "lon_span",
            "observations"
        ]
    ].describe()
)

Number of cyclones: 264
Median duration: 81.0 hours
Median latitude span: 3.95 degrees
Median longitude span: 6.3 degrees

Summary:

       duration_hours    lat_span    lon_span  observations
count      264.000000  264.000000  264.000000    264.000000
mean        97.181818    5.158333    7.896591     33.397727
std         67.690676    4.360906    6.950479     22.564587
min          0.000000    0.000000    0.000000      1.000000
25%         45.000000    1.800000    2.975000     16.000000
50%         81.000000    3.950000    6.300000     28.000000
75%        138.000000    7.600000   10.500000     47.000000
max        336.000000   23.300000   43.600000    113.000000

In [ ]:
# ============================================
# HOW MANY CYCLONE POINTS PER HOUR?
# ============================================

points_per_hour = (
    era5_lookup
    .groupby("ERA5_TIME")
    .size()
)

print("Unique hours:", len(points_per_hour))
print("Maximum points in one hour:", points_per_hour.max())
print("Average points per hour:", round(points_per_hour.mean(), 2))

display(points_per_hour.value_counts().sort_index().tail(10))

Unique hours: 8217
Maximum points in one hour: 3
Average points per hour: 1.07

1    7630
2     574
3      13
Name: count, dtype: int64

In [ ]:
# ============================================
# TEST: 10 UNIQUE LOCATIONS, MULTIPLE TIMES
# ============================================

test_locations = (
    era5_lookup[
        ["ERA5_LAT", "ERA5_LON"]
    ]
    .drop_duplicates()
    .head(10)
)

print("Testing locations:")
display(test_locations)

Testing locations:

       ERA5_LAT  ERA5_LON
53226      7.50     90.00
53227      8.00     89.50
53228      8.50     89.00
53229      9.00     89.00
53230      9.50     89.00
53231     10.00     88.50
53232     10.75     88.25
53233     11.50     88.00
53234     12.00     88.00
53237     12.25     88.00

In [ ]:
# ============================================
# Retrieve time series for these 10 locations
# ============================================

test_lat = test_locations["ERA5_LAT"].values
test_lon = test_locations["ERA5_LON"].values

test_geo = ds[
    ["u10", "v10", "t2m", "d2m", "msl", "sst"]
].sel(
    latitude=xr.DataArray(test_lat, dims="location"),
    longitude=xr.DataArray(test_lon, dims="location"),
    method="nearest"
)

print(test_geo)

<xarray.Dataset> Size: 188MB
Dimensions:    (time: 759960, location: 10)
Coordinates:
  * time       (time) datetime64[ns] 6MB 1940-01-01 ... 2026-09-10T23:00:00
    latitude   (location) float64 80B 7.5 8.0 8.5 9.0 ... 10.75 11.5 12.0 12.25
    longitude  (location) float64 80B 90.0 89.5 89.0 89.0 ... 88.0 88.0 88.0
Dimensions without coordinates: location
Data variables:
    u10        (time, location) float32 30MB dask.array<chunksize=(67584, 10), meta=np.ndarray>
    v10        (time, location) float32 30MB dask.array<chunksize=(67584, 10), meta=np.ndarray>
    t2m        (time, location) float32 30MB dask.array<chunksize=(67584, 10), meta=np.ndarray>
    d2m        (time, location) float32 30MB dask.array<chunksize=(67584, 10), meta=np.ndarray>
    msl        (time, location) float32 30MB dask.array<chunksize=(67584, 10), meta=np.ndarray>
    sst        (time, location) float32 30MB dask.array<chunksize=(67584, 10), meta=np.ndarray>
Attributes:
    Conventions:             CF-1.7
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_edition:            1
    GRIB_subCentre:          0
    history:                 2024-09-02T04:48 GRIB to CDM+CF via cfgrib-0.9.1...
    institution:             European Centre for Medium-Range Weather Forecasts

In [ ]:
# ============================================
# TEST: TIME + LOCATION RESTRICTED EXTRACTION
# ============================================

test_rows = era5_lookup.head(10).copy()

test_times = test_rows["ERA5_TIME"].values
test_lats = test_rows["LAT"].values
test_lons = test_rows["LON"].values

# Only request the time range containing these observations
time_start = pd.Timestamp(test_times.min())
time_end = pd.Timestamp(test_times.max())

print("Time range:", time_start, "to", time_end)

test_geo_small = ds[
    ["u10", "v10", "t2m", "d2m", "msl", "sst"]
].sel(
    time=slice(time_start, time_end),
    latitude=slice(30, 0),
    longitude=slice(40, 100)
)

print(test_geo_small)

Time range: 2000-03-27 12:00:00 to 2000-03-28 15:00:00
<xarray.Dataset> Size: 2kB
Dimensions:    (time: 28, latitude: 0, longitude: 241)
Coordinates:
  * time       (time) datetime64[ns] 224B 2000-03-27T12:00:00 ... 2000-03-28T...
  * latitude   (latitude) float64 0B
  * longitude  (longitude) float64 2kB 40.0 40.25 40.5 ... 99.5 99.75 100.0
Data variables:
    u10        (time, latitude, longitude) float32 0B dask.array<chunksize=(28, 0, 4), meta=np.ndarray>
    v10        (time, latitude, longitude) float32 0B dask.array<chunksize=(28, 0, 4), meta=np.ndarray>
    t2m        (time, latitude, longitude) float32 0B dask.array<chunksize=(28, 0, 4), meta=np.ndarray>
    d2m        (time, latitude, longitude) float32 0B dask.array<chunksize=(28, 0, 4), meta=np.ndarray>
    msl        (time, latitude, longitude) float32 0B dask.array<chunksize=(28, 0, 4), meta=np.ndarray>
    sst        (time, latitude, longitude) float32 0B dask.array<chunksize=(28, 0, 4), meta=np.ndarray>
Attributes:
    Conventions:             CF-1.7
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_edition:            1
    GRIB_subCentre:          0
    history:                 2024-09-02T04:48 GRIB to CDM+CF via cfgrib-0.9.1...
    institution:             European Centre for Medium-Range Weather Forecasts

In [ ]:
# ============================================
# TEST: LOAD SMALL TIME-RESTRICTED ERA5 BLOCK
# ============================================

print("Loading small ERA5 block...")

test_loaded_small = test_geo_small.compute()

print("SUCCESS!")
print(test_loaded_small)

Loading small ERA5 block...
SUCCESS!
<xarray.Dataset> Size: 2kB
Dimensions:    (time: 28, latitude: 0, longitude: 241)
Coordinates:
  * time       (time) datetime64[ns] 224B 2000-03-27T12:00:00 ... 2000-03-28T...
  * latitude   (latitude) float64 0B
  * longitude  (longitude) float64 2kB 40.0 40.25 40.5 ... 99.5 99.75 100.0
Data variables:
    u10        (time, latitude, longitude) float32 0B
    v10        (time, latitude, longitude) float32 0B
    t2m        (time, latitude, longitude) float32 0B
    d2m        (time, latitude, longitude) float32 0B
    msl        (time, latitude, longitude) float32 0B
    sst        (time, latitude, longitude) float32 0B
Attributes:
    Conventions:             CF-1.7
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_edition:            1
    GRIB_subCentre:          0
    history:                 2024-09-02T04:48 GRIB to CDM+CF via cfgrib-0.9.1...
    institution:             European Centre for Medium-Range Weather Forecasts

In [ ]:
# ============================================
# TEST: ONE CYCLONE ERA5 BLOCK
# ============================================

# Take the first cyclone
storm = storm_ranges.iloc[0]

print("Cyclone:", storm["NAME"])
print("SID:", storm["SID"])
print("Time:", storm["start_time"], "to", storm["end_time"])
print("Latitude:", storm["min_lat"], "to", storm["max_lat"])
print("Longitude:", storm["min_lon"], "to", storm["max_lon"])

# Select ONLY this cyclone's time and spatial region
storm_block = ds_time[
    ["u10", "v10", "t2m", "d2m", "msl", "sst"]
].sel(
    time=slice(storm["start_time"], storm["end_time"]),
    latitude=slice(storm["min_lat"], storm["max_lat"]),
    longitude=slice(storm["min_lon"], storm["max_lon"])
)

print("\nSelected ERA5 block:")
print(storm_block)

Cyclone: UNNAMED
SID: 2000088N08090
Time: 2000-03-27 12:00:00 to 2000-03-30 12:00:00
Latitude: 7.5 to 16.0
Longitude: 88.0 to 90.5

Selected ERA5 block:
<xarray.Dataset> Size: 675kB
Dimensions:    (time: 73, latitude: 35, longitude: 11)
Coordinates:
  * time       (time) datetime64[ns] 584B 2000-03-27T12:00:00 ... 2000-03-30T...
  * latitude   (latitude) float64 280B 7.5 7.75 8.0 8.25 ... 15.5 15.75 16.0
  * longitude  (longitude) float64 88B 88.0 88.25 88.5 88.75 ... 90.0 90.25 90.5
Data variables:
    u10        (time, latitude, longitude) float32 112kB dask.array<chunksize=(1, 35, 11), meta=np.ndarray>
    v10        (time, latitude, longitude) float32 112kB dask.array<chunksize=(1, 35, 11), meta=np.ndarray>
    t2m        (time, latitude, longitude) float32 112kB dask.array<chunksize=(1, 35, 11), meta=np.ndarray>
    d2m        (time, latitude, longitude) float32 112kB dask.array<chunksize=(1, 35, 11), meta=np.ndarray>
    msl        (time, latitude, longitude) float32 112kB dask.array<chunksize=(1, 35, 11), meta=np.ndarray>
    sst        (time, latitude, longitude) float32 112kB dask.array<chunksize=(1, 35, 11), meta=np.ndarray>
Attributes:
    Conventions:             CF-1.7
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_edition:            1
    GRIB_subCentre:          0
    history:                 2024-09-02T04:48 GRIB to CDM+CF via cfgrib-0.9.1...
    institution:             European Centre for Medium-Range Weather Forecasts

In [ ]:
# ============================================
# Load the one-cyclone ERA5 block
# ============================================

print("Loading cyclone ERA5 block...")

storm_block_loaded = storm_block.compute()

print("SUCCESS!")
print(storm_block_loaded)

Loading cyclone ERA5 block...
SUCCESS!
<xarray.Dataset> Size: 675kB
Dimensions:    (time: 73, latitude: 35, longitude: 11)
Coordinates:
  * time       (time) datetime64[ns] 584B 2000-03-27T12:00:00 ... 2000-03-30T...
  * latitude   (latitude) float64 280B 7.5 7.75 8.0 8.25 ... 15.5 15.75 16.0
  * longitude  (longitude) float64 88B 88.0 88.25 88.5 88.75 ... 90.0 90.25 90.5
Data variables:
    u10        (time, latitude, longitude) float32 112kB -1.216 ... -7.628
    v10        (time, latitude, longitude) float32 112kB 5.547 5.459 ... 2.992
    t2m        (time, latitude, longitude) float32 112kB 298.8 298.6 ... 300.2
    d2m        (time, latitude, longitude) float32 112kB 296.3 296.5 ... 297.0
    msl        (time, latitude, longitude) float32 112kB 1.007e+05 ... 1.006e+05
    sst        (time, latitude, longitude) float32 112kB 302.2 302.2 ... 301.3
Attributes:
    Conventions:             CF-1.7
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_edition:            1
    GRIB_subCentre:          0
    history:                 2024-09-02T04:48 GRIB to CDM+CF via cfgrib-0.9.1...
    institution:             European Centre for Medium-Range Weather Forecasts

In [ ]:
# ============================================================
# FULL IBTrACS + ERA5 EXTRACTION
# ============================================================

import time
from IPython.display import clear_output

# Variables we need
ERA5_VARS = ["u10", "v10", "t2m", "d2m", "msl", "sst"]

# Padding around each cyclone's bounding box
PADDING = 0.5

# Store results here
all_results = []

total_storms = len(storm_ranges)

print(f"Starting ERA5 extraction for {total_storms} cyclones...")
print("=" * 60)

for storm_num, (_, storm) in enumerate(storm_ranges.iterrows(), start=1):

    sid = storm["SID"]

    # --------------------------------------------------------
    # Get all IBTrACS observations belonging to this cyclone
    # --------------------------------------------------------

    storm_obs = era5_lookup[
        era5_lookup["SID"] == sid
    ].copy()

    if len(storm_obs) == 0:
        continue

    # --------------------------------------------------------
    # Define padded ERA5 extraction region
    # --------------------------------------------------------

    lat_min = max(0, storm["min_lat"] - PADDING)
    lat_max = min(30, storm["max_lat"] + PADDING)

    lon_min = max(40, storm["min_lon"] - PADDING)
    lon_max = min(100, storm["max_lon"] + PADDING)

    # --------------------------------------------------------
    # Retrieve only this cyclone's time + spatial block
    # --------------------------------------------------------

    try:

        storm_era5 = ds_time[ERA5_VARS].sel(
            time=slice(
                storm["start_time"],
                storm["end_time"]
            ),
            latitude=slice(
                lat_min,
                lat_max
            ),
            longitude=slice(
                lon_min,
                lon_max
            )
        ).compute()

        # ----------------------------------------------------
        # Extract each IBTrACS observation locally
        # ----------------------------------------------------

        for _, obs in storm_obs.iterrows():

            try:

                point = storm_era5.sel(
                    time=obs["ERA5_TIME"],
                    latitude=obs["LAT"],
                    longitude=obs["LON"],
                    method="nearest"
                )

                all_results.append({
                    "SID": obs["SID"],
                    "SEASON": obs["SEASON"],
                    "NAME": obs["NAME"],
                    "ISO_TIME": obs["ISO_TIME"],
                    "LAT": obs["LAT"],
                    "LON": obs["LON"],
                    "USA_WIND": obs["USA_WIND"],
                    "USA_PRES": obs["USA_PRES"],

                    "ERA5_TIME": pd.Timestamp(
                        point["time"].values
                    ),

                    "ERA5_LAT": float(
                        point["latitude"].values
                    ),

                    "ERA5_LON": float(
                        point["longitude"].values
                    ),

                    "u10": float(
                        point["u10"].values
                    ),

                    "v10": float(
                        point["v10"].values
                    ),

                    "t2m": float(
                        point["t2m"].values
                    ),

                    "d2m": float(
                        point["d2m"].values
                    ),

                    "msl": float(
                        point["msl"].values
                    ),

                    "sst": float(
                        point["sst"].values
                    )
                })

            except Exception as point_error:

                print(
                    f"  Point error for {sid}: "
                    f"{point_error}"
                )

        # ----------------------------------------------------
        # Progress
        # ----------------------------------------------------

        print(
            f"[{storm_num:3d}/{total_storms}] "
            f"{storm['NAME']:<12} "
            f"| observations: {len(storm_obs):3d} "
            f"| extracted: {len(all_results):5d}"
        )

    except Exception as storm_error:

        print(
            f"ERROR in storm {sid}: "
            f"{storm_error}"
        )

print("=" * 60)
print("EXTRACTION COMPLETE!")
print("Total extracted observations:", len(all_results))

Starting ERA5 extraction for 264 cyclones...
============================================================
[  1/264] UNNAMED      | observations:  25 | extracted:    25
[  2/264] UNNAMED      | observations:   8 | extracted:    33
[  3/264] UNNAMED      | observations:  37 | extracted:    70
[  4/264] UNNAMED      | observations:  30 | extracted:   100
[  5/264] UNNAMED      | observations:  80 | extracted:   180
[  6/264] UNNAMED      | observations:  48 | extracted:   228

KeyboardInterrupt:

In [ ]:
# ============================================================
# FULL EXTRACTION — BATCH SETUP
# ============================================================

BATCH_SIZE = 25

total_storms = len(storm_ranges)

print("Total cyclones:", total_storms)
print("Batch size:", BATCH_SIZE)
print("Number of batches:",
      (total_storms + BATCH_SIZE - 1) // BATCH_SIZE)

Total cyclones: 264
Batch size: 25
Number of batches: 11

In [ ]:
# ============================================================
# EXTRACT BATCH 1
# ============================================================

BATCH_NUMBER = 1

start_idx = (BATCH_NUMBER - 1) * BATCH_SIZE
end_idx = min(BATCH_NUMBER * BATCH_SIZE, total_storms)

batch_storms = storm_ranges.iloc[start_idx:end_idx]

print(
    f"Processing cyclones {start_idx + 1} "
    f"to {end_idx}"
)

print("Number of cyclones in this batch:", len(batch_storms))

Processing cyclones 1 to 25
Number of cyclones in this batch: 25

In [ ]:
# ============================================================
# BATCH EXTRACTION — BATCH 1
# ============================================================

import gc
import time

BATCH_NUMBER = 1
BATCH_SIZE = 25

start_idx = (BATCH_NUMBER - 1) * BATCH_SIZE
end_idx = min(BATCH_NUMBER * BATCH_SIZE, len(storm_ranges))

batch_storms = storm_ranges.iloc[start_idx:end_idx]

print(f"Starting Batch {BATCH_NUMBER}")
print(f"Cyclones: {start_idx + 1} → {end_idx}")
print("=" * 60)

batch_results = []

ERA5_VARS = ["u10", "v10", "t2m", "d2m", "msl", "sst"]
PADDING = 0.5

batch_start_time = time.time()

for storm_num, (_, storm) in enumerate(batch_storms.iterrows(), start=start_idx + 1):

    sid = storm["SID"]

    # Get IBTrACS observations for this cyclone
    storm_obs = era5_lookup[
        era5_lookup["SID"] == sid
    ].copy()

    if len(storm_obs) == 0:
        continue

    # Small padded geographic region
    lat_min = max(0, storm["min_lat"] - PADDING)
    lat_max = min(30, storm["max_lat"] + PADDING)

    lon_min = max(40, storm["min_lon"] - PADDING)
    lon_max = min(100, storm["max_lon"] + PADDING)

    try:

        # Retrieve only this cyclone's ERA5 block
        storm_era5 = ds_time[ERA5_VARS].sel(
            time=slice(
                storm["start_time"],
                storm["end_time"]
            ),
            latitude=slice(
                lat_min,
                lat_max
            ),
            longitude=slice(
                lon_min,
                lon_max
            )
        ).compute()

        # Match each IBTrACS observation locally
        for _, obs in storm_obs.iterrows():

            point = storm_era5.sel(
                time=obs["ERA5_TIME"],
                latitude=obs["LAT"],
                longitude=obs["LON"],
                method="nearest"
            )

            batch_results.append({
                "SID": obs["SID"],
                "SEASON": obs["SEASON"],
                "NAME": obs["NAME"],
                "ISO_TIME": obs["ISO_TIME"],
                "LAT": obs["LAT"],
                "LON": obs["LON"],
                "USA_WIND": obs["USA_WIND"],
                "USA_PRES": obs["USA_PRES"],

                "ERA5_TIME": pd.Timestamp(
                    point["time"].values
                ),

                "ERA5_LAT": float(
                    point["latitude"].values
                ),

                "ERA5_LON": float(
                    point["longitude"].values
                ),

                "u10": float(point["u10"].values),
                "v10": float(point["v10"].values),
                "t2m": float(point["t2m"].values),
                "d2m": float(point["d2m"].values),
                "msl": float(point["msl"].values),
                "sst": float(point["sst"].values)
            })

        print(
            f"[{storm_num:3d}/264] "
            f"{storm['NAME']:<12} | "
            f"Obs: {len(storm_obs):3d} | "
            f"Batch extracted: {len(batch_results):4d}"
        )

        # Free the cyclone block before moving on
        del storm_era5
        gc.collect()

    except Exception as e:

        print(
            f"ERROR — cyclone {sid} "
            f"({storm['NAME']}): {e}"
        )

# ============================================================
# SAVE BATCH
# ============================================================

batch_df = pd.DataFrame(batch_results)

batch_filename = f"era5_batch_{BATCH_NUMBER:02d}.csv"

batch_df.to_csv(
    batch_filename,
    index=False
)

elapsed = time.time() - batch_start_time

print("=" * 60)
print(f"BATCH {BATCH_NUMBER} COMPLETE")
print(f"Rows extracted: {len(batch_df)}")
print(f"Saved as: {batch_filename}")
print(f"Time taken: {elapsed / 60:.2f} minutes")

Starting Batch 1
Cyclones: 1 → 25
============================================================
[  1/264] UNNAMED      | Obs:  25 | Batch extracted:   25
[  2/264] UNNAMED      | Obs:   8 | Batch extracted:   33
[  3/264] UNNAMED      | Obs:  37 | Batch extracted:   70
[  4/264] UNNAMED      | Obs:  30 | Batch extracted:  100
[  5/264] UNNAMED      | Obs:  80 | Batch extracted:  180
[  6/264] UNNAMED      | Obs:  48 | Batch extracted:  228
[  7/264] UNNAMED      | Obs:  67 | Batch extracted:  295
[  8/264] UNNAMED      | Obs:  12 | Batch extracted:  307
[  9/264] UNNAMED      | Obs:  37 | Batch extracted:  344
[ 10/264] UNNAMED      | Obs:  41 | Batch extracted:  385
[ 11/264] UNNAMED      | Obs:  19 | Batch extracted:  404
[ 12/264] UNNAMED      | Obs:  27 | Batch extracted:  431
[ 13/264] VAMEI        | Obs:  29 | Batch extracted:  460
[ 14/264] UNNAMED      | Obs:  41 | Batch extracted:  501
[ 15/264] UNNAMED      | Obs:  27 | Batch extracted:  528
[ 16/264] UNNAMED      | Obs:  12 | Batch extracted:  540
[ 17/264] UNNAMED      | Obs:  24 | Batch extracted:  564
[ 18/264] UNNAMED      | Obs:  47 | Batch extracted:  611
[ 19/264] UNNAMED      | Obs:  38 | Batch extracted:  649
[ 20/264] UNNAMED      | Obs:  92 | Batch extracted:  741
[ 21/264] UNNAMED      | Obs:  25 | Batch extracted:  766
[ 22/264] UNNAMED      | Obs:   9 | Batch extracted:  775
[ 23/264] UNNAMED      | Obs:  28 | Batch extracted:  803
[ 24/264] UNNAMED      | Obs:  32 | Batch extracted:  835
[ 25/264] UNNAMED      | Obs:  63 | Batch extracted:  898
============================================================
BATCH 1 COMPLETE
Rows extracted: 898
Saved as: era5_batch_01.csv
Time taken: 61.13 minutes