<a href="https://colab.research.google.com/github/TTS-77/Cyclone-AI/blob/main/Notebook/IBTrACS_Testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#IBTrACS Data Set Testing

In [ ]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)
print("Environment ready! 🚀")

Pandas version: 2.2.3
NumPy version: 2.1.3
Environment ready! 🚀

In [ ]:
from google.colab import files
import pandas as pd

uploaded = files.upload()

print("Uploaded files:")
for filename in uploaded:
    print(filename)

Saving amphan_ibtracs.csv.xlsx to amphan_ibtracs.csv.xlsx
Uploaded files:
amphan_ibtracs.csv.xlsx

In [ ]:
# Load the Amphan IBTrACS dataset

ibtracs = pd.read_excel("amphan_ibtracs.csv.xlsx")

print("Dataset loaded successfully!")
print("Shape:", ibtracs.shape)

print("\nColumns:")
print(ibtracs.columns.tolist())

print("\nFirst 5 rows:")
display(ibtracs.head())

Dataset loaded successfully!
Shape: (51, 8)

Columns:
['SID', 'SEASON', 'NAME', 'ISO_TIME', 'LAT', 'LON', 'USA_WIND', 'USA_PRES']

First 5 rows:

,SID,SEASON,NAME,ISO_TIME,LAT,LON,USA_WIND,USA_PRES
0,2020136N10088,2020,AMPHAN,2020-05-15 06:00:00,9.5,87.5,20,1007
1,2020136N10088,2020,AMPHAN,2020-05-15 09:00:00,9.5,87.2,25,1005
2,2020136N10088,2020,AMPHAN,2020-05-15 12:00:00,9.5,87.0,30,1002
3,2020136N10088,2020,AMPHAN,2020-05-15 15:00:00,9.5,86.8,30,1002
4,2020136N10088,2020,AMPHAN,2020-05-15 18:00:00,9.5,86.6,30,1001

In [ ]:
# Clean important columns

# Convert timestamp to proper datetime
ibtracs["ISO_TIME"] = pd.to_datetime(ibtracs["ISO_TIME"])

# Convert latitude and longitude to numeric
ibtracs["LAT"] = pd.to_numeric(ibtracs["LAT"], errors="coerce")
ibtracs["LON"] = pd.to_numeric(ibtracs["LON"], errors="coerce")

# Convert wind and pressure to numeric
# Invalid/missing values become NaN
ibtracs["USA_WIND"] = pd.to_numeric(ibtracs["USA_WIND"], errors="coerce")
ibtracs["USA_PRES"] = pd.to_numeric(ibtracs["USA_PRES"], errors="coerce")

print("Data types after cleaning:")
print(ibtracs.dtypes)

print("\nMissing values:")
print(ibtracs.isna().sum())

print("\nTime range:")
print(ibtracs["ISO_TIME"].min(), "to", ibtracs["ISO_TIME"].max())

print("\nLatitude range:")
print(ibtracs["LAT"].min(), "to", ibtracs["LAT"].max())

print("\nLongitude range:")
print(ibtracs["LON"].min(), "to", ibtracs["LON"].max())

Data types after cleaning:
SID                 object
SEASON               int64
NAME                object
ISO_TIME    datetime64[ns]
LAT                float64
LON                float64
USA_WIND           float64
USA_PRES           float64
dtype: object

Missing values:
SID         0
SEASON      0
NAME        0
ISO_TIME    0
LAT         0
LON         0
USA_WIND    2
USA_PRES    2
dtype: int64

Time range:
2020-05-15 06:00:00 to 2020-05-21 12:00:00

Latitude range:
9.5 to 25.4

Longitude range:
86.1 to 90.1

In [ ]:
from google.colab import files

print("Select your ERA5 CSV file:")
era5_upload = files.upload()

print("\nUploaded:")
for filename in era5_upload:
    print(filename)

Select your ERA5 CSV file:

Saving reanalysis-era5-single-levels-timeseries-sfcl75tfp1f.csv to reanalysis-era5-single-levels-timeseries-sfcl75tfp1f (1).csv

Uploaded:
reanalysis-era5-single-levels-timeseries-sfcl75tfp1f (1).csv

In [ ]:
# Import Pandas again
import pandas as pd

# Load the ERA5 dataset
era5_filename = list(era5_upload.keys())[0]

era5 = pd.read_csv(era5_filename)

print("ERA5 dataset loaded successfully!")
print("Shape:", era5.shape)

print("\nColumns:")
print(era5.columns.tolist())

print("\nFirst 5 rows:")
display(era5.head())

ERA5 dataset loaded successfully!
Shape: (192, 9)

Columns:
['valid_time', 'latitude', 'longitude', 'u10', 'v10', 'd2m', 't2m', 'msl', 'sst']

First 5 rows:

,valid_time,latitude,longitude,u10,v10,d2m,t2m,msl,sst
0,2020-05-16 00:00:00,10.00,86.00,7.707123,-1.234009,298.13562,301.47528,99720.00,303.60498
1,2020-05-16 00:00:00,10.00,86.25,7.410248,2.336304,298.62195,300.92060,99736.00,303.58154
2,2020-05-16 00:00:00,10.25,86.00,2.398529,-2.310181,298.39734,301.41083,99679.50,303.60790
3,2020-05-16 00:00:00,10.25,86.25,1.752045,2.488647,298.47546,300.72723,99690.50,303.57960
4,2020-05-16 01:00:00,10.00,86.00,7.135788,-1.002258,298.65290,301.72864,99720.19,303.60498

In [ ]:
# Clean ERA5 data

# Convert timestamp to datetime
era5["valid_time"] = pd.to_datetime(era5["valid_time"])

# Convert coordinates and weather variables to numeric
numeric_columns = [
    "latitude",
    "longitude",
    "u10",
    "v10",
    "d2m",
    "t2m",
    "msl",
    "sst"
]

for col in numeric_columns:
    era5[col] = pd.to_numeric(era5[col], errors="coerce")

print("ERA5 data types:")
print(era5.dtypes)

print("\nMissing values:")
print(era5.isna().sum())

print("\nERA5 time range:")
print(era5["valid_time"].min(), "to", era5["valid_time"].max())

print("\nERA5 coordinates:")
print("Latitude:", era5["latitude"].unique())
print("Longitude:", era5["longitude"].unique())

ERA5 data types:
valid_time    datetime64[ns]
latitude             float64
longitude            float64
u10                  float64
v10                  float64
d2m                  float64
t2m                  float64
msl                  float64
sst                  float64
dtype: object

Missing values:
valid_time    0
latitude      0
longitude     0
u10           0
v10           0
d2m           0
t2m           0
msl           0
sst           0
dtype: int64

ERA5 time range:
2020-05-16 00:00:00 to 2020-05-17 23:00:00

ERA5 coordinates:
Latitude: [10.   10.25]
Longitude: [86.   86.25]

In [ ]:
import pandas as pd

# Load IBTrACS
ibtracs = pd.read_excel("amphan_ibtracs.csv.xlsx")

# Clean column names
ibtracs.columns = ibtracs.columns.str.strip()

# Convert time
ibtracs["ISO_TIME"] = pd.to_datetime(ibtracs["ISO_TIME"])

# Convert wind and pressure to numeric
ibtracs["USA_WIND"] = pd.to_numeric(ibtracs["USA_WIND"], errors="coerce")
ibtracs["USA_PRES"] = pd.to_numeric(ibtracs["USA_PRES"], errors="coerce")

print("IBTrACS loaded successfully!")
print("Shape:", ibtracs.shape)

display(ibtracs.head())

IBTrACS loaded successfully!
Shape: (51, 8)

,SID,SEASON,NAME,ISO_TIME,LAT,LON,USA_WIND,USA_PRES
0,2020136N10088,2020,AMPHAN,2020-05-15 06:00:00,9.5,87.5,20.0,1007.0
1,2020136N10088,2020,AMPHAN,2020-05-15 09:00:00,9.5,87.2,25.0,1005.0
2,2020136N10088,2020,AMPHAN,2020-05-15 12:00:00,9.5,87.0,30.0,1002.0
3,2020136N10088,2020,AMPHAN,2020-05-15 15:00:00,9.5,86.8,30.0,1002.0
4,2020136N10088,2020,AMPHAN,2020-05-15 18:00:00,9.5,86.6,30.0,1001.0

In [ ]:
# Check how much of the IBTrACS track falls inside our ERA5 dataset

print("IBTrACS time range:")
print(ibtracs["ISO_TIME"].min(), "to", ibtracs["ISO_TIME"].max())

print("\nERA5 time range:")
print(era5["valid_time"].min(), "to", era5["valid_time"].max())

print("\nIBTrACS coordinate range:")
print(
    "Latitude:", ibtracs["LAT"].min(), "to", ibtracs["LAT"].max()
)
print(
    "Longitude:", ibtracs["LON"].min(), "to", ibtracs["LON"].max()
)

print("\nERA5 coordinate range:")
print(
    "Latitude:", era5["latitude"].min(), "to", era5["latitude"].max()
)
print(
    "Longitude:", era5["longitude"].min(), "to", era5["longitude"].max()
)

# Find IBTrACS observations whose timestamp exists in ERA5
time_overlap = ibtracs[
    ibtracs["ISO_TIME"].isin(era5["valid_time"])
]

print("\nIBTrACS observations with matching ERA5 timestamps:",
      len(time_overlap))

display(time_overlap[
    ["ISO_TIME", "LAT", "LON", "USA_WIND", "USA_PRES"]
].head(15))

IBTrACS time range:
2020-05-15 06:00:00 to 2020-05-21 12:00:00

ERA5 time range:
2020-05-16 00:00:00 to 2020-05-17 23:00:00

IBTrACS coordinate range:
Latitude: 9.5 to 25.4
Longitude: 86.1 to 90.1

ERA5 coordinate range:
Latitude: 10.0 to 10.25
Longitude: 86.0 to 86.25

IBTrACS observations with matching ERA5 timestamps: 16

              ISO_TIME   LAT   LON  USA_WIND  USA_PRES
6  2020-05-16 00:00:00   9.8  86.4      35.0     999.0
7  2020-05-16 03:00:00  10.1  86.2      38.0     998.0
8  2020-05-16 06:00:00  10.3  86.1      40.0     997.0
9  2020-05-16 09:00:00  10.5  86.1      45.0     995.0
10 2020-05-16 12:00:00  10.6  86.2      50.0     992.0
11 2020-05-16 15:00:00  10.8  86.1      53.0     990.0
12 2020-05-16 18:00:00  10.9  86.1      55.0     987.0
13 2020-05-16 21:00:00  11.1  86.1      58.0     985.0
14 2020-05-17 00:00:00  11.2  86.1      60.0     982.0
15 2020-05-17 03:00:00  11.3  86.1      65.0     980.0
16 2020-05-17 06:00:00  11.5  86.2      70.0     978.0
17 2020-05-17 09:00:00  11.6  86.2      75.0     974.0
18 2020-05-17 12:00:00  11.9  86.2      80.0     970.0
19 2020-05-17 15:00:00  12.5  86.4     100.0     951.0
20 2020-05-17 18:00:00  12.5  86.4     120.0     932.0

In [ ]:
import os

print("Files in Colab:")
print(os.listdir())

Files in Colab:
['.config', 'amphan_ibtracs.csv.xlsx', 'd84af37cfb54d5ad8316584f97c6fa07.grib', 'reanalysis-era5-single-levels-timeseries-sfcl75tfp1f (1).csv', 'reanalysis-era5-single-levels-timeseries-sfcl75tfp1f.csv', 'sample_data']